git config --global core.autocrlf false
git config --global core.safecrlf false
git config --local core.autocrlf false
git config --local core.safecrlf false

@set remote_path=\\192.168.4.249\诺亚内\程序部\sy沙鹰\手游\config
@set remote_map=\\192.168.4.249\诺亚内\程序部\sy沙鹰\手游\mapData

@if '%1' neq '' (@set remote_path=%1)
@if '%2' neq '' (@set remote_map=%2)

@set gameServerPath=..\Bin\GameServer
@set worldServerPath=..\Bin\WorldServer
@set centerServerPath=..\Bin\CenterServer
@set loginServerPath=..\Bin\LoginServer
@set publicServerPath=..\Bin\PublicServer
@set commonPath=..\Bin\lua
@set offlineAiPath=..\Bin\offlineAi
@set mergeServerPath=..\Bin\MergeServer
@set activeServerPath=..\Bin\MergeServer

@echo 将配置文件拷贝到对应目录
@echo ----------------------------------------------------------------------------------
@echo 拷贝game server配置文件
copy /Y "%remote_path%\mecha\mechaInbornDevice.lua" "%gameServerPath%\data\mecha\mechaInbornDevice.lua"
copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\questions.lua" "%gameServerPath%\data\activity\worldAnswer\questions.lua"
copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\worldAnswerConfig.lua" "%gameServerPath%\data\activity\worldAnswer\worldAnswerConfig.lua"
copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\worldAnswerReward.lua" "%gameServerPath%\data\activity\worldAnswer\worldAnswerReward.lua"
copy /Y "%remote_path%\activity\serverBattleAwardConfig.lua" "%gameServerPath%\data\activity\serverBattleAwardConfig.lua"
copy /Y "%remote_path%\raidCommonPage\raidPageData.lua" "%gameServerPath%\data\raidCommonPage\raidPageData.lua"
copy /Y "%remote_path%\firstWeekRank\firstWeekRankCommonConfig.lua" "%gameServerPath%\data\firstWeekRank\firstWeekRankCommonConfig.lua"
copy /Y "%remote_path%\firstWeekRank\firstWeekRankReward.lua" "%gameServerPath%\data\firstWeekRank\firstWeekRankReward.lua"
copy /Y "%remote_path%\jobChallenge\jobChallengePassReward.lua" "%gameServerPath%\data\jobChallenge\jobChallengePassReward.lua"
copy /Y "%remote_path%\jobChallenge\jobChallengeRankReward.lua" "%gameServerPath%\data\jobChallenge\jobChallengeRankReward.lua"
copy /Y "%remote_path%\jobChallenge\jobChallengeLevelConfig.lua" "%gameServerPath%\data\jobChallenge\jobChallengeLevelConfig.lua"
copy /Y "%remote_path%\corps\corpsParty.lua" "%gameServerPath%\data\corps\corpsParty.lua"
copy /Y "%remote_path%\newRecruitsCorps\newRecruitsCorpsSystemMember.lua" "%gameServerPath%\data\corps\newRecruitsCorpsSystemMember.lua"
copy /Y "%remote_path%\newRecruitsCorps\newRecruitsCorpsCommon.lua" "%gameServerPath%\data\corps\newRecruitsCorpsCommon.lua"
copy /Y "%remote_path%\festivalEvent\holidayGift\holidayAward.lua" "%gameServerPath%\data\festivalEvent\holidayGift\holidayAward.lua"
copy /Y "%remote_path%\festivalEvent\holidayGift\holidayConfig.lua" "%gameServerPath%\data\festivalEvent\holidayGift\holidayConfig.lua"
copy /Y "%remote_path%\festivalEvent\holidayGift\holidayList.lua" "%gameServerPath%\data\festivalEvent\holidayGift\holidayList.lua"
copy /Y "%remote_path%\springActivity\cNYStoreTabData.lua" "%gameServerPath%\data\springActivity\cNYStoreTabData.lua"
copy /Y "%remote_path%\springActivity\cNYStoreGoods.lua" "%gameServerPath%\data\springActivity\cNYStoreGoods.lua"
copy /Y "%remote_path%\springActivity\cNYActivenessCommon.lua" "%gameServerPath%\data\springActivity\cNYActivenessCommon.lua"
copy /Y "%remote_path%\springActivity\cNYActivenessReward.lua" "%gameServerPath%\data\springActivity\cNYActivenessReward.lua"
copy /Y "%remote_path%\chat\textEmojSingle.lua" "%gameServerPath%\data\chat\textEmojSingle.lua"
copy /Y "%remote_path%\corps\corpsNewMemberGift.lua" "%gameServerPath%\data\corps\corpsNewMemberGift.lua"
copy /Y "%remote_path%\corps\corpsGrowthQuest.lua" "%gameServerPath%\data\corps\corpsGrowthQuest.lua"
copy /Y "%remote_path%\role\roleHateRate.lua" "%gameServerPath%\data\role\roleHateRate.lua"
copy /Y "%remote_path%\dominate\dominateLocation.lua" "%gameServerPath%\data\dominate\dominateLocation.lua"
copy /Y "%remote_path%\dominate\dominateExtraDrop.lua" "%gameServerPath%\data\dominate\dominateExtraDrop.lua"
copy /Y "%remote_path%\dominate\dominateConfig.lua" "%gameServerPath%\data\dominate\dominateConfig.lua"
copy /Y "%remote_path%\common\constConfig.lua" "%gameServerPath%\data\const\constConfig.lua"
copy /Y "%remote_path%\role\roleInitAttr.lua" "%gameServerPath%\data\role\roleInitAttr.lua"
copy /Y "%remote_path%\role\reliveMoney.lua" "%gameServerPath%\data\role\reliveMoney.lua"
copy /Y "%remote_path%\role\reliveTime.lua" "%gameServerPath%\data\role\reliveTime.lua"
copy /Y "%remote_path%\role\citizenship.lua" "%gameServerPath%\data\role\citizenship.lua"
copy /Y "%remote_path%\role\levelAttrAllRoles.lua" "%gameServerPath%\data\role\levelAttrAllRoles.lua"
copy /Y "%remote_path%\role\levelExpLimit.lua" "%gameServerPath%\data\role\levelExpLimit.lua"
copy /Y "%remote_path%\role\roleBornMapConfig.lua" "%gameServerPath%\data\role\roleBornMapConfig.lua"
copy /Y "%remote_path%\robot\robotPlayerAttr.lua" "%gameServerPath%\data\role\robotPlayerAttr.lua"
copy /Y "%remote_path%\role\rushRegister.lua" "%gameServerPath%\data\role\rushRegister.lua"
copy /Y "%remote_path%\role\roleLevelUpMail.lua" "%gameServerPath%\data\role\roleLevelUpMail.lua"
copy /Y "%remote_path%\monster\monsterBase.lua" "%gameServerPath%\data\monster\monsterBase.lua"
copy /Y "%remote_path%\monster\monsterAttr.lua" "%gameServerPath%\data\monster\monsterAttr.lua"
copy /Y "%remote_path%\monster\monsterDrop.lua" "%gameServerPath%\data\monster\monsterDrop.lua"
copy /Y "%remote_path%\monster\monsterAi.lua" "%gameServerPath%\data\monster\monsterAi.lua"
copy /Y "%remote_path%\monster\specialMonsterAttr.lua" "%gameServerPath%\data\monster\specialMonsterAttr.lua"
copy /Y "%remote_path%\monster\monsterInitiativeSkill.lua" "%gameServerPath%\data\monster\monsterInitiativeSkill.lua"
copy /Y "%remote_path%\monster\monsterSpecialDrop.lua" "%gameServerPath%\data\monster\monsterSpecialDrop.lua"
copy /Y "%remote_path%\monster\monsterCommonAttack.lua" "%gameServerPath%\data\monster\monsterCommonAttack.lua"
copy /Y "%remote_path%\monster\monsterDead.lua" "%gameServerPath%\data\monster\monsterDead.lua"
copy /Y "%remote_path%\monster\standardMonsterAttr.lua" "%gameServerPath%\data\monster\standardMonsterAttr.lua"
copy /Y "%remote_path%\npc\npcBase.lua" "%gameServerPath%\data\npc\npcBase.lua"
copy /Y "%remote_path%\npc\npcAi.lua" "%gameServerPath%\data\npc\npcAi.lua"
copy /Y "%remote_path%\npc\collectionBase.lua" "%gameServerPath%\data\npc\collectionBase.lua"
copy /Y "%remote_path%\quest\questData.lua" "%gameServerPath%\data\quest\questData.lua"
copy /Y "%remote_path%\quest\questBuffAction.lua" "%gameServerPath%\data\quest\questBuffAction.lua"
copy /Y "%remote_path%\quest\questTransmit.lua" "%gameServerPath%\data\quest\questTransmit.lua"
copy /Y "%remote_path%\quest\questServerLimit.lua" "%gameServerPath%\data\quest\questServerLimit.lua"
copy /Y "%remote_path%\quest\questSpecialPush.lua" "%gameServerPath%\data\quest\questSpecialPush.lua"
copy /Y "%remote_path%\quest\questSuggest.lua" "%gameServerPath%\data\quest\questSuggest.lua"
copy /Y "%remote_path%\taskChain\assistanceRewards.lua" "%gameServerPath%\data\taskChain\assistanceRewards.lua"
copy /Y "%remote_path%\taskChain\TaskData.lua" "%gameServerPath%\data\taskChain\TaskData.lua"
copy /Y "%remote_path%\taskChain\taskChainRewards.lua" "%gameServerPath%\data\taskChain\taskChainRewards.lua"
copy /Y "%remote_path%\taskChain\taskRatio.lua" "%gameServerPath%\data\taskChain\taskRatio.lua"
copy /Y "%remote_path%\taskChain\taskStatus.lua" "%gameServerPath%\data\taskChain\taskStatus.lua"
copy /Y "%remote_path%\taskChain\taskType.lua" "%gameServerPath%\data\taskChain\taskType.lua"
copy /Y "%remote_path%\taskChain\corpsTaskRewards.lua" "%gameServerPath%\data\taskChain\corpsTaskRewards.lua"
copy /Y "%remote_path%\taskChain\shoutText.lua" "%gameServerPath%\data\taskChain\shoutText.lua"
copy /Y "%remote_path%\taskChain\cropsTaskSpecialRing.lua" "%gameServerPath%\data\taskChain\cropsTaskSpecialRing.lua"
copy /Y "%remote_path%\quest\questStepData.lua" "%gameServerPath%\data\quest\questStepData.lua"
copy /Y "%remote_path%\quest\questRewardData.lua" "%gameServerPath%\data\quest\questRewardData.lua"
copy /Y "%remote_path%\quest\subStepData.lua" "%gameServerPath%\data\quest\subStepData.lua"
copy /Y "%remote_path%\quest\federalQuestAward.lua" "%gameServerPath%\data\quest\federalQuestAward.lua"
copy /Y "%remote_path%\quest\newGrowthData.lua" "%gameServerPath%\data\quest\newGrowthData.lua"
copy /Y "%remote_path%\quest\questEquipAttr.lua" "%gameServerPath%\data\quest\questEquipAttr.lua"
copy /Y "%remote_path%\quest\questVerify.lua" "%gameServerPath%\data\quest\questVerify.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderAirWallByPoint.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderAirWallByPoint.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderCommonConfig.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderCommonConfig.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderMonByServerLvl.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderMonByServerLvl.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderMonConfig.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderMonConfig.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderPointByServerLvl.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderPointByServerLvl.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderQuestReward.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderQuestReward.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderQuestRewardRatio.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderQuestRewardRatio.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderRaidConfig.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderRaidConfig.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderRewardBySeverLvl.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderRewardBySeverLvl.lua"
copy /Y "%remote_path%\raid\wantedOrder\wantedOrderVoiceAnswerQues.lua" "%gameServerPath%\data\raid\wantedOrder\wantedOrderVoiceAnswerQues.lua"
copy /Y "%remote_path%\fightingCapacity" "%gameServerPath%\data\fightingCapacity"

copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\questions.lua" "%centerServerPath%\data\activity\worldAnswer\questions.lua"
copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\worldAnswerConfig.lua" "%centerServerPath%\data\activity\worldAnswer\worldAnswerConfig.lua"
copy /Y "%remote_path%\activities\openServerActivities\worldAnswer\worldAnswerReward.lua" "%centerServerPath%\data\activity\worldAnswer\worldAnswerReward.lua"
copy /Y "%remote_path%\jobChallenge\jobChallengeRankReward.lua" "%centerServerPath%\data\jobChallenge\jobChallengeRankReward.lua"
copy /Y "%remote_path%\firstWeekRank\firstWeekRankReward.lua" "%centerServerPath%\data\firstWeekRank\firstWeekRankReward.lua"
copy /Y "%remote_path%\firstWeekRank\firstWeekRankTime.lua" "%centerServerPath%\data\firstWeekRank\firstWeekRankTime.lua"
copy /Y "%remote_path%\item\itemCommon.lua" "%centerServerPath%\data\config\item\itemCommon.lua"
copy /Y "%remote_path%\item\itemCommon.lua" "%gameServerPath%\data\config\item\itemCommon.lua"
copy /Y "%remote_path%\item\animalRewardInfo.lua" "%gameServerPath%\data\config\item\animalRewardInfo.lua"
copy /Y "%remote_path%\item\itemScriptData.lua" "%gameServerPath%\data\config\item\itemScriptData.lua"
copy /Y "%remote_path%\item\itemValue.lua" "%gameServerPath%\data\config\item\itemValue.lua"
copy /Y "%remote_path%\item\randombox.lua" "%gameServerPath%\data\config\item\randombox.lua"
copy /Y "%remote_path%\item\selectBox.lua" "%gameServerPath%\data\config\item\selectBox.lua"
copy /Y "%remote_path%\item\materialSynthesis.lua" "%gameServerPath%\data\config\item\materialSynthesis.lua"
copy /Y "%remote_path%\item\itemBatchUse.lua" "%gameServerPath%\data\config\item\itemBatchUse.lua"
copy /Y "%remote_path%\detector\detectorMonster.lua" "%gameServerPath%\data\config\detector\detectorMonster.lua"
copy /Y "%remote_path%\detector\detectorLocation.lua" "%gameServerPath%\data\config\detector\detectorLocation.lua"
copy /Y "%remote_path%\detector\detectorReward.lua" "%gameServerPath%\data\config\detector\detectorReward.lua"
copy /Y "%remote_path%\detector\advancedDetectorReward.lua" "%gameServerPath%\data\config\detector\advancedDetectorReward.lua"
copy /Y "%remote_path%\map\mapConfig.lua" "%gameServerPath%\data\map\mapConfig\mapConfig.lua"
copy /Y "%remote_path%\map\gameServerInitMapConfig.lua" "%gameServerPath%\data\map\mapConfig\gameServerInitMapConfig.lua"
copy /Y "%remote_path%\map\mapPkType.lua" "%gameServerPath%\data\map\mapConfig\mapPkType.lua"
copy /Y "%remote_path%\map\fastChangeMap.lua" "%gameServerPath%\data\map\mapConfig\fastChangeMap.lua"
copy /Y "%remote_path%\map\transportData.lua" "%gameServerPath%\data\map\mapConfig\mapTransportConfig.lua"
copy /Y "%remote_path%\map\quickTransformCommon.lua" "%gameServerPath%\data\map\mapConfig\quickTransformCommon.lua"
copy /Y "%remote_map%\mapEditData" "%gameServerPath%\data\map\mapEditData"
copy /Y "%remote_map%\navmeshFile" "%gameServerPath%\data\map\navmeshFile"
copy /Y "%remote_path%\EventEditor" "%gameServerPath%\data\eventEditor"
copy /Y "%remote_path%\raid\raidConfig.lua" "%gameServerPath%\data\raid\raidConfig.lua"
copy /Y "%remote_path%\raid\raidAwardTimes.lua" "%gameServerPath%\data\raid\raidAwardTimes.lua"
copy /Y "%remote_path%\raid\battlefieldRewards.lua" "%gameServerPath%\data\raid\battlefieldRewards.lua"
copy /Y "%remote_path%\raid\crystalCanyon\killScore.lua" "%gameServerPath%\data\raid\crystalCanyon\killScore.lua"
copy /Y "%remote_path%\raid\crystalCanyon\crysMonsters.lua" "%gameServerPath%\data\raid\crystalCanyon\crysMonsters.lua"
copy /Y "%remote_path%\raid\crystalCanyon\battlefieldConfiguration.lua" "%gameServerPath%\data\raid\crystalCanyon\battlefieldConfiguration.lua"
copy /Y "%remote_path%\raid\crystalCanyon\battlefieldEventConfig.lua" "%gameServerPath%\data\raid\crystalCanyon\battlefieldEventConfig.lua"
copy /Y "%remote_path%\store\storeData.lua" "%gameServerPath%\data\store\storeData.lua"
copy /Y "%remote_path%\store\storeItemSet.lua" "%gameServerPath%\data\store\storeItemSet.lua"
copy /Y "%remote_path%\store\storeShowLimitData.lua" "%gameServerPath%\data\store\storeShowLimitData.lua"
copy /Y "%remote_path%\store\goldStoreRefresh.lua" "%gameServerPath%\data\store\goldStoreRefresh.lua"
copy /Y "%remote_path%\store\goldStoreForSale.lua" "%gameServerPath%\data\store\goldStoreForSale.lua"
copy /Y "%remote_path%\store\quickIndexForItemStore.lua" "%gameServerPath%\data\store\quickIndexForItemStore.lua"
copy /Y "%remote_path%\store\gospelLotteryAward.lua" "%gameServerPath%\data\store\gospelLotteryAward.lua"
copy /Y "%remote_path%\chat\tipsFilter.lua" "%gameServerPath%\data\chat\tipsFilter.lua"
copy /Y "%remote_path%\misc\strDef.lua" "%gameServerPath%\data\misc\strDef.lua"
copy /Y "%remote_path%\misc\progressData.lua" "%gameServerPath%\data\misc\progressData.lua"
copy /Y "%remote_path%\gm\realPlayerAttr.lua" "%gameServerPath%\data\gm\realPlayerAttr.lua"

copy /Y "%remote_path%\raid\huntDemon\huntDemonLocation.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonLocation.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonCommon.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonCommon.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonLocation.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonLocation.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonRefresh.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonRefresh.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonBase.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonBase.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonRefreshPos.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonRefreshPos.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonReward.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonReward.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonRewardExp.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonRewardExp.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonAwardLevel.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonAwardLevel.lua"
copy /Y "%remote_path%\raid\huntDemon\huntDemonReFreshLv.lua" "%gameServerPath%\data\raid\huntDemon\huntDemonReFreshLv.lua"

copy /Y "%remote_path%\home\homeWorkshopLimitConfig.lua" "%gameServerPath%\data\home\homeWorkshopLimitConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopMakeConfig.lua" "%gameServerPath%\data\home\homeWorkshopMakeConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopReplaceConfig.lua" "%gameServerPath%\data\home\homeWorkshopReplaceConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopUpConfig.lua" "%gameServerPath%\data\home\homeWorkshopUpConfig.lua"

copy /Y "%remote_path%\raid\SeizeTreasureJonsButton.lua" "%gameServerPath%\data\raid\seizeTreasureJons\seizeTreasureJonsButton.lua"
copy /Y "%remote_path%\raid\seizeTreasureJons\seizeTreasureJonsConfig.lua" "%gameServerPath%\data\raid\seizeTreasureJons\seizeTreasureJonsBaseConfig.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\normalGameFightAward.lua" "%gameServerPath%\data\raid\starArts\normalGameFightAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\normalGameMailAward.lua" "%gameServerPath%\data\raid\starArts\normalGameMailAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\finalGameRankingAward.lua" "%gameServerPath%\data\raid\starArts\finalGameRankingAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\starBattleConfiguration.lua" "%gameServerPath%\data\raid\starArts\starBattleConfiguration.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\rolePositionInfo.lua" "%gameServerPath%\data\raid\starArts\rolePositionInfo.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\divisionConfiguration.lua" "%gameServerPath%\data\raid\starArts\divisionConfiguration.lua"

copy /Y "%remote_path%\raid\worldBoss\worldBossBase.lua" "%gameServerPath%\data\raid\worldBoss\worldBossBase.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCommon.lua" "%gameServerPath%\data\raid\worldBoss\worldBossCommon.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossReward.lua" "%gameServerPath%\data\raid\worldBoss\worldBossReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCoinDrop.lua" "%gameServerPath%\data\raid\worldBoss\worldBossCoinDrop.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossBoxPos.lua" "%gameServerPath%\data\raid\worldBoss\worldBossBoxPos.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossSecondStageBase.lua" "%gameServerPath%\data\raid\worldBoss\worldBossSecondStageBase.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossSecondStageReward.lua" "%gameServerPath%\data\raid\worldBoss\worldBossSecondStageReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPersonGoals.lua" "%gameServerPath%\data\raid\worldBoss\worldBossPersonGoals.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCorpsGoals.lua" "%gameServerPath%\data\raid\worldBoss\worldBossCorpsGoals.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossFirstStageDamage.lua" "%gameServerPath%\data\raid\worldBoss\worldBossFirstStageDamage.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossFirstStagePersonGoals.lua" "%gameServerPath%\data\raid\worldBoss\worldBossFirstStagePersonGoals.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCommonNew.lua" "%gameServerPath%\data\raid\worldBoss\worldBossCommonNew.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPrepareTimeReward.lua" "%gameServerPath%\data\raid\worldBoss\worldBossPrepareTimeReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPrepareTimeConfig.lua" "%gameServerPath%\data\raid\worldBoss\worldBossPrepareTimeConfig.lua"


copy /Y "%remote_path%\raid\speciesZerg\zergLotteryClass.lua" "%gameServerPath%\data\raid\speciesZerg\zergLotteryClass.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergLotteryLevel.lua" "%gameServerPath%\data\raid\speciesZerg\zergLotteryLevel.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergMonsterLevel.lua" "%gameServerPath%\data\raid\speciesZerg\zergMonsterLevel.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergRaidAward.lua" "%gameServerPath%\data\raid\speciesZerg\zergRaidAward.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergCollection.lua" "%gameServerPath%\data\raid\speciesZerg\zergCollection.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergCommon.lua" "%gameServerPath%\data\raid\speciesZerg\zergCommon.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergMonsterDrop.lua" "%gameServerPath%\data\raid\speciesZerg\zergMonsterDrop.lua"
copy /Y "%remote_path%\raid\speciesZerg\zergExpPearl.lua" "%gameServerPath%\data\raid\speciesZerg\zergExpPearl.lua"

copy /Y "%remote_path%\pveTower\levelReward.lua" "%gameServerPath%\data\raid\pveTower\levelReward.lua"
copy /Y "%remote_path%\pveTower\levelRewardCommon.lua" "%gameServerPath%\data\raid\pveTower\levelRewardCommon.lua"
copy /Y "%remote_path%\pveTower\towerLotteryBase.lua" "%gameServerPath%\data\raid\pveTower\towerLotteryBase.lua"
copy /Y "%remote_path%\pveTower\rankingsAward.lua" "%gameServerPath%\data\raid\pveTower\rankingsAward.lua"
copy /Y "%remote_path%\pveTower\pveTowerBase.lua" "%gameServerPath%\data\raid\pveTower\pveTowerBase.lua"
copy /Y "%remote_path%\pveTower\oldLevelConfig.lua" "%gameServerPath%\data\raid\pveTower\oldLevelConfig.lua"


copy /Y "%remote_path%\home\furnitureConfig.lua" "%gameServerPath%\data\home\furnitureConfig.lua"
copy /Y "%remote_path%\home\furnitureConstant.lua" "%gameServerPath%\data\home\furnitureConstant.lua"

copy /Y "%remote_path%\chat\mutualAction.lua" "%gameServerPath%\data\chat\mutualAction.lua"
copy /Y "%remote_path%\chat\chatCommonConfig.lua" "%gameServerPath%\data\chat\chatCommonConfig.lua"
copy /Y "%remote_path%\chat\channelLimitConfig.lua" "%gameServerPath%\data\chat\channelLimitConfig.lua"
copy /Y "%remote_path%\chat\bubblingBase.lua" "%gameServerPath%\data\chat\bubblingBase.lua"
copy /Y "%remote_path%\chat\bubblingData.lua" "%gameServerPath%\data\chat\bubblingData.lua"
copy /Y "%remote_path%\chat\VipToIndexBubbling.lua" "%gameServerPath%\data\chat\VipToIndexBubbling.lua"
copy /Y "%remote_path%\team\teamCommonConfig.lua" "%gameServerPath%\data\team\teamCommonConfig.lua"

copy /Y "%remote_path%\raid\raidTeamlimit.lua" "%gameServerPath%\data\raid\raidTeamlimit.lua"

copy /Y "%remote_path%\skillAI\skillAI.lua" "%gameServerPath%\lua\config\skill\skillAI.lua"
copy /Y "%remote_path%\battle" "%gameServerPath%\data\config\battle"

copy /Y "%remote_path%\mecha\mechaAbilityGroup.lua" "%gameServerPath%\data\mecha\mechaAbilityGroup.lua"
copy /Y "%remote_path%\mecha\mechaAbilityGroupRollValue.lua" "%gameServerPath%\data\mecha\mechaAbilityGroupRollValue.lua"
::copy /Y "%remote_path%\mecha\mechaArmsGroup.lua" "%gameServerPath%\data\mecha\mechaArmsGroup.lua"
copy /Y "%remote_path%\mecha\mechaAdvance.lua" "%gameServerPath%\data\mecha\mechaAdvance.lua"
copy /Y "%remote_path%\mecha\mechaBase.lua" "%gameServerPath%\data\mecha\mechaBase.lua"
copy /Y "%remote_path%\mecha\mechaBattleAttr.lua" "%gameServerPath%\data\mecha\mechaBattleAttr.lua"
copy /Y "%remote_path%\mecha\mechaBattleCount.lua" "%gameServerPath%\data\mecha\mechaBattleCount.lua"
copy /Y "%remote_path%\mecha\mechaBorn.lua" "%gameServerPath%\data\mecha\mechaBorn.lua"
copy /Y "%remote_path%\mecha\mechaCommon.lua" "%gameServerPath%\data\mecha\mechaCommon.lua"
copy /Y "%remote_path%\mecha\mechaDevice.lua" "%gameServerPath%\data\mecha\mechaDevice.lua"
copy /Y "%remote_path%\mecha\mechaDeviceGroup.lua" "%gameServerPath%\data\mecha\mechaDeviceGroup.lua"
copy /Y "%remote_path%\mecha\mechaDeviceLv.lua" "%gameServerPath%\data\mecha\mechaDeviceLv.lua"
copy /Y "%remote_path%\mecha\mechaExp.lua" "%gameServerPath%\data\mecha\mechaExp.lua"
copy /Y "%remote_path%\mecha\mechaGuard.lua" "%gameServerPath%\data\mecha\mechaGuard.lua"
copy /Y "%remote_path%\mecha\mechaGuardRandom.lua" "%gameServerPath%\data\mecha\mechaGuardRandom.lua"
copy /Y "%remote_path%\mecha\mechaInitAttr.lua" "%gameServerPath%\data\mecha\mechaInitAttr.lua"
copy /Y "%remote_path%\mecha\mechaSkillDesc.lua" "%gameServerPath%\data\mecha\mechaSkillDesc.lua"
::copy /Y "%remote_path%\mecha\mechaStunt.lua" "%gameServerPath%\data\mecha\mechaStunt.lua"
::copy /Y "%remote_path%\mecha\mechaTalent.lua" "%gameServerPath%\data\mecha\mechaTalent.lua"
copy /Y "%remote_path%\mecha\mechaZizhidan.lua" "%gameServerPath%\data\mecha\mechaZizhidan.lua"
copy /Y "%remote_path%\mecha\mechaBattleAttr.lua" "%gameServerPath%\data\mecha\mechaBattleAttr.lua"
copy /Y "%remote_path%\mecha\mechaFourAttr.lua" "%gameServerPath%\data\mecha\mechaFourAttr.lua"
copy /Y "%remote_path%\mecha\mechaCorpSkill.lua" "%gameServerPath%\data\mecha\mechaCorpSkill.lua"
copy /Y "%remote_path%\mecha\mechaTalk.lua" "%gameServerPath%\data\mecha\mechaTalk.lua"
copy /Y "%remote_path%\mecha\mechaInitConfig.lua" "%gameServerPath%\data\mecha\mechaInitConfig.lua"

copy /Y "%remote_path%\home\iExploreConstant.lua" "%gameServerPath%\data\home\iExploreConstant.lua"
copy /Y "%remote_path%\home\homeConstant.lua" "%gameServerPath%\data\home\homeConstant.lua"
copy /Y "%remote_path%\home\roomBuildConfig.lua" "%gameServerPath%\data\home\roomBuildConfig.lua"
copy /Y "%remote_path%\equip" "%gameServerPath%\data\config\equip"

copy /Y "%remote_path%\raid\specialSpaceKillPeople.lua" "%gameServerPath%\data\raid\specialSpace\specialSpaceKillPeople.lua"
copy /Y "%remote_path%\monster\severLevelMonter.lua" "%gameServerPath%\data\raid\specialSpace\severLevelMonter.lua"
copy /Y "%remote_path%\monster\specialSpaceMonter.lua" "%gameServerPath%\data\raid\specialSpace\specialSpaceMonter.lua"
copy /Y "%remote_path%\monster\specialSpaceMonterBorn.lua" "%gameServerPath%\data\raid\specialSpace\specialSpaceMonterBorn.lua"
copy /Y "%remote_path%\raid\specialSpace\specialSpaceCommon.lua" "%gameServerPath%\data\raid\specialSpace\specialSpaceCommon.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSpecialSpaceKillPeople.lua" "%gameServerPath%\data\raid\specialSpace\crossSpecialSpaceKillPeople.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSeverLevelMonter.lua" "%gameServerPath%\data\raid\specialSpace\crossSeverLevelMonter.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSpecialSpaceMonter.lua" "%gameServerPath%\data\raid\specialSpace\crossSpecialSpaceMonter.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSpecialSpaceMonterBorn.lua" "%gameServerPath%\data\raid\specialSpace\crossSpecialSpaceMonterBorn.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSpecialSpaceCommon.lua" "%gameServerPath%\data\raid\specialSpace\crossSpecialSpaceCommon.lua"
copy /Y "%remote_path%\raid\crossSpecialSpace\crossSpecialSpaceBossDrop.lua" "%gameServerPath%\data\raid\specialSpace\crossSpecialSpaceBossDrop.lua"

copy /Y "%remote_path%\msgBox\msgDef.lua" "%gameServerPath%\data\msgBox\msgDef.lua"

copy /Y "%remote_path%\raid\peakChallenge\challengeConfiguration.lua" "%gameServerPath%\data\raid\peakChallenge\challengeConfiguration.lua"
copy /Y "%remote_path%\raid\peakChallenge\monsterCoefficient.lua" "%gameServerPath%\data\raid\peakChallenge\monsterCoefficient.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeReward.lua" "%gameServerPath%\data\raid\peakChallenge\challengeReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\playoffsReward.lua" "%gameServerPath%\data\raid\peakChallenge\playoffsReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\listOfMonsters.lua" "%gameServerPath%\data\raid\peakChallenge\listOfMonsters.lua"
copy /Y "%remote_path%\raid\peakChallenge\peakChallengeConfiguration.lua" "%gameServerPath%\data\raid\peakChallenge\peakChallengeConfiguration.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeReward.lua" "%gameServerPath%\data\raid\peakChallenge\challengeReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeFailReward.lua" "%gameServerPath%\data\raid\peakChallenge\challengeFailReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\boxCollection.lua" "%gameServerPath%\data\raid\peakChallenge\boxCollection.lua"
copy /Y "%remote_path%\raid\starbattle" "%gameServerPath%\data\raid\starWar"

copy /Y "%remote_path%\battle\commonBuff.lua" "%gameServerPath%\data\config\battle\commonBuff.lua"
copy /Y "%remote_path%\battle\resBuffDisplayDesc.lua" "%gameServerPath%\data\config\battle\resBuffDisplayDesc.lua"
copy /Y "%remote_path%\battle\ratioResistPro.lua" "%gameServerPath%\data\config\battle\ratioResistPro.lua"

copy /Y "%remote_path%\item\drugNum.lua" "%gameServerPath%\data\config\item\drugNum.lua"
copy /Y "%remote_path%\item\drugAttrType.lua" "%gameServerPath%\data\config\item\drugAttrType.lua"

copy /Y "%remote_path%\chip\chipAchievement.lua" "%gameServerPath%\data\config\chip\chipAchievement.lua"
copy /Y "%remote_path%\chip\chipItem.lua" "%gameServerPath%\data\config\chip\chipItem.lua"
copy /Y "%remote_path%\chip\chipLimit.lua" "%gameServerPath%\data\config\chip\chipLimit.lua"
copy /Y "%remote_path%\chip\chipSplit.lua" "%gameServerPath%\data\config\chip\chipSplit.lua"
copy /Y "%remote_path%\chip\chipCompose.lua" "%gameServerPath%\data\config\chip\chipCompose.lua"
copy /Y "%remote_path%\chip\chipQuickCompose.lua" "%gameServerPath%\data\config\chip\chipQuickCompose.lua"

copy /Y "%remote_path%\title\titleBase.lua" "%gameServerPath%\data\title\titleBase.lua"
copy /Y "%remote_path%\title\achieveBase.lua" "%gameServerPath%\data\achieve\achieveBase.lua"
copy /Y "%remote_path%\title\achievementReward.lua" "%gameServerPath%\data\achieve\achievementReward.lua"

copy /Y "%remote_path%\energyField\energyFieldConfiguration.lua" "%gameServerPath%\data\energyField\energyFieldConfiguration.lua"
copy /Y "%remote_path%\energyField\energyFieldExp.lua" "%gameServerPath%\data\energyField\energyFieldExp.lua"
copy /Y "%remote_path%\energyField\monsterElite.lua" "%gameServerPath%\data\energyField\monsterElite.lua"
copy /Y "%remote_path%\energyField\accumulator.lua" "%gameServerPath%\data\energyField\accumulator.lua"
copy /Y "%remote_path%\energyField\newAccumulator.lua" "%gameServerPath%\data\energyField\newAccumulator.lua"
copy /Y "%remote_path%\energyField\autoFightAward.lua" "%gameServerPath%\data\energyField\autoFightAward.lua"
copy /Y "%remote_path%\energyField\autoFightMapConfig.lua" "%gameServerPath%\data\energyField\autoFightMapConfig.lua"

copy /Y "%remote_path%\raid\timeVortex\timeVortexCommon.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexCommon.lua"
copy /Y "%remote_path%\raid\timeVortex\timeVortexReward.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexReward.lua"
copy /Y "%remote_path%\raid\timeVortex\timeVortexScore.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexScore.lua"
copy /Y "%remote_path%\raid\timeVortex\timeVortexRefreshPos.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexRefreshPos.lua"
copy /Y "%remote_path%\raid\timeVortex\timeVortexRewardDrop.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexRewardDrop.lua"
copy /Y "%remote_path%\raid\timeVortex\timeVortexAreaDam.lua" "%gameServerPath%\data\raid\timeVortex\timeVortexAreaDam.lua"

copy /Y "%remote_path%\raid\raidPersonalTargets.lua" "%gameServerPath%\data\raid\raidPersonalTargets.lua"

copy /Y "%remote_path%\raid\serverbattle\serverBattleCommon.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleCommon.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleMonsterCheck.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleMonsterCheck.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleSeasonAward.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleSeasonAward.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceAward.lua" "%gameServerPath%\data\raid\serverBattle\serverBattlePerRaceAward.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleCorpAucitonRate.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleCorpAucitonRate.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleCorpAucitonRule.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleCorpAucitonRule.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleGloryBroadcast.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleGloryBroadcast.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleBaseModelMap.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleBaseModelMap.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleConfig.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleConfig.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceTreasureBox.lua" "%gameServerPath%\data\raid\serverBattle\serverBattlePerRaceTreasureBox.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceWinTimeRate.lua" "%gameServerPath%\data\raid\serverBattle\serverBattlePerRaceWinTimeRate.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleSpecialAward.lua" "%gameServerPath%\data\raid\serverBattle\serverBattleSpecialAward.lua"

copy /Y "%remote_path%\militaryRank\militaryRank.lua" "%gameServerPath%\data\militaryRank\militaryRank.lua"
copy /Y "%remote_path%\militaryRank\oldToNewMilitary.lua" "%gameServerPath%\data\militaryRank\oldToNewMilitary.lua"
copy /Y "%remote_path%\militaryRank\militaryRankMainType.lua" "%gameServerPath%\data\militaryRank\militaryRankMainType.lua"
copy /Y "%remote_path%\militaryRank\militaryRankChildType.lua" "%gameServerPath%\data\militaryRank\militaryRankChildType.lua"
copy /Y "%remote_path%\militaryRank\extraSub\militaryRankSubAwardEquip.lua" "%gameServerPath%\data\militaryRank\militaryRankSubAwardEquip.lua"
copy /Y "%remote_path%\militaryRank\extraSub\militaryRankSubAwardItem.lua" "%gameServerPath%\data\militaryRank\militaryRankSubAwardItem.lua"
copy /Y "%remote_path%\militaryRank\extraSub\militaryRankSubUnlockMount.lua" "%gameServerPath%\data\militaryRank\militaryRankSubUnlockMount.lua"

copy /Y "%remote_path%\friend\friendlyConfig.lua" "%gameServerPath%\data\friend\friendlyConfig.lua"
copy /Y "%remote_path%\friend\friendlyLevel.lua" "%gameServerPath%\data\friend\friendlyLevel.lua"
copy /Y "%remote_path%\friend\flowerConfig.lua" "%gameServerPath%\data\friend\flowerConfig.lua"
copy /Y "%remote_path%\gameHelper\entriesConfig.lua" "%gameServerPath%\data\robot\entriesConfig.lua"

copy /Y "%remote_path%\stall\boothConfiguration.lua" "%gameServerPath%\data\stall\boothConfiguration.lua"
copy /Y "%remote_path%\stall\boothCoordinates.lua" "%gameServerPath%\data\stall\boothCoordinates.lua"

copy /Y "%remote_path%\raid\allSidesAmbush\allSidesAmbushInfo.lua" "%gameServerPath%\data\raid\allSidesAmbush\allSidesAmbushInfo.lua"
copy /Y "%remote_path%\raid\allSidesAmbush\allSidesMonsterAward.lua" "%gameServerPath%\data\raid\allSidesAmbush\allSidesMonsterAward.lua"
copy /Y "%remote_path%\raid\allSidesAmbush\allSidesRaidAward.lua" "%gameServerPath%\data\raid\allSidesAmbush\allSidesRaidAward.lua"
copy /Y "%remote_path%\raid\allSidesAmbush\allSidesRaidExp.lua" "%gameServerPath%\data\raid\allSidesAmbush\allSidesRaidExp.lua"

copy /Y "%remote_path%\score\popularityConfig.lua" "%gameServerPath%\data\score\popularityConfig.lua"
copy /Y "%remote_path%\score\scoreConfig.lua" "%gameServerPath%\data\score\scoreConfig.lua"
copy /Y "%remote_path%\score\transferVIPScore.lua" "%gameServerPath%\data\score\transferVIPScore.lua"
copy /Y "%remote_path%\welfare\bindingPhone.lua" "%gameServerPath%\data\benefit\bindingPhone.lua"
copy /Y "%remote_path%\welfare\dailyGiftBag.lua" "%gameServerPath%\data\benefit\dailyGiftBag.lua"
copy /Y "%remote_path%\welfare\dailyGiftDashButtonBag.lua" "%gameServerPath%\data\benefit\dailyGiftDashButtonBag.lua"
copy /Y "%remote_path%\welfare\fund.lua" "%gameServerPath%\data\benefit\fund.lua"
copy /Y "%remote_path%\welfare\ingotGiftBag.lua" "%gameServerPath%\data\benefit\ingotGiftBag.lua"
copy /Y "%remote_path%\welfare\levelGiftBag.lua" "%gameServerPath%\data\benefit\levelGiftBag.lua"
copy /Y "%remote_path%\welfare\offlineExperience.lua" "%gameServerPath%\data\benefit\offlineExperience.lua"
copy /Y "%remote_path%\welfare\offlineExperienceNumber.lua" "%gameServerPath%\data\benefit\offlineExperienceNumber.lua"
copy /Y "%remote_path%\welfare\dailySign.lua" "%gameServerPath%\data\benefit\dailySign.lua"
copy /Y "%remote_path%\welfare\accumulativeSign.lua" "%gameServerPath%\data\benefit\accumulativeSign.lua"
copy /Y "%remote_path%\welfare\sevenDaysLogin.lua" "%gameServerPath%\data\benefit\sevenDaysLogin.lua"
copy /Y "%remote_path%\welfare\onlineReward.lua" "%gameServerPath%\data\benefit\onlineReward.lua"
copy /Y "%remote_path%\welfare\sevenDayPackage.lua" "%gameServerPath%\data\benefit\sevenDayPackage.lua"
copy /Y "%remote_path%\welfare\deleteFileReward.lua" "%gameServerPath%\data\benefit\deleteFileReward.lua"
copy /Y "%remote_path%\newPlayer\newPlayerTreasure.lua" "%gameServerPath%\data\newPlayer\newPlayerTreasure.lua"
copy /Y "%remote_path%\newPlayer\newPlayerEquip.lua" "%gameServerPath%\data\newPlayer\newPlayerEquip.lua"

copy /Y "%remote_path%\luckyWheel\luckyWheelAward.lua" "%gameServerPath%\data\benefit\luckyWheelAward.lua"
copy /Y "%remote_path%\luckyWheel\luckyWheelCommon.lua" "%gameServerPath%\data\benefit\luckyWheelCommon.lua"
copy /Y "%remote_path%\luckyWheel\luckyWheelDefine.lua" "%gameServerPath%\data\benefit\luckyWheelDefine.lua"

copy /Y "%remote_path%\carrier\carrierBase.lua" "%gameServerPath%\data\carrier\carrierBase.lua"

copy /Y "%remote_path%\aircraft\aircraftBaseConfig.lua" "%gameServerPath%\data\aircraft\aircraftBaseConfig.lua"
copy /Y "%remote_path%\aircraft\aircraftStageConfig.lua" "%gameServerPath%\data\aircraft\aircraftStageConfig.lua"
copy /Y "%remote_path%\aircraft\aircraftCommandConfig.lua" "%gameServerPath%\data\aircraft\aircraftCommandConfig.lua"

copy /Y "%remote_path%\vIP\vipBase.lua" "%gameServerPath%\data\vip\vipBase.lua"
copy /Y "%remote_path%\vIP\vipPower.lua" "%gameServerPath%\data\vip\vipPower.lua"
copy /Y "%remote_path%\vIP\vipPush.lua" "%gameServerPath%\data\vip\vipPush.lua"

copy /Y "%remote_path%\guide\guideConfig.lua" "%gameServerPath%\data\quest\guideConfig.lua"
copy /Y "%remote_path%\guide\guideForgeEquipConfig.lua" "%gameServerPath%\data\quest\guideForgeEquipConfig.lua"
copy /Y "%remote_path%\activity\activityOpenConfig.lua" "%gameServerPath%\data\activity\activityOpenConfig.lua"

copy /Y "%remote_path%\corpsParty\corpPartyBase.lua" "%gameServerPath%\data\raid\corpsParty\corpPartyBase.lua"
copy /Y "%remote_path%\corpsParty\corpPartyExp.lua" "%gameServerPath%\data\raid\corpsParty\corpPartyExp.lua"
copy /Y "%remote_path%\corpsParty\corpPartyIndex.lua" "%gameServerPath%\data\raid\corpsParty\corpPartyIndex.lua"
copy /Y "%remote_path%\corpsParty\corpQuestion.lua" "%gameServerPath%\data\raid\corpsParty\corpQuestion.lua"
copy /Y "%remote_path%\corpsParty\corpQuestionReward.lua" "%gameServerPath%\data\raid\corpsParty\corpQuestionReward.lua"
copy /Y "%remote_path%\corpsParty\partyBoxLocation.lua" "%gameServerPath%\data\raid\corpsParty\partyBoxLocation.lua"
copy /Y "%remote_path%\corpsParty\partyChangeModel.lua" "%gameServerPath%\data\raid\corpsParty\partyChangeModel.lua"
copy /Y "%remote_path%\corpsParty\partyCollection.lua" "%gameServerPath%\data\raid\corpsParty\partyCollection.lua"
copy /Y "%remote_path%\raid\openRaid.lua" "%gameServerPath%\data\raid\openRaid.lua"

copy /Y "%remote_path%\battle\traps.lua" "%gameServerPath%\data\config\battle\traps.lua"
copy /Y "%remote_path%\store\goldPurchase.lua" "%gameServerPath%\data\store\goldPurchase.lua"
copy /Y "%remote_path%\store\purchaseRebate.lua" "%gameServerPath%\data\store\purchaseRebate.lua"
copy /Y "%remote_path%\store\purchaseRebateEquip.lua" "%gameServerPath%\data\store\purchaseRebateEquip.lua"
copy /Y "%remote_path%\store\purchaseAreaLimit.lua" "%gameServerPath%\data\store\purchaseAreaLimit.lua"
copy /Y "%remote_path%\store\paidActivity\levelLimitStore.lua" "%gameServerPath%\data\store\levelLimitStore.lua"
copy /Y "%remote_path%\store\paymentPoint.lua" "%gameServerPath%\data\store\paymentPoint.lua"

copy /Y "%remote_path%\corps\corpsCommon.lua" "%gameServerPath%\data\corps\corpsCommon.lua"
copy /Y "%remote_path%\corps\corpSkillAttr.lua" "%gameServerPath%\data\corps\corpSkillAttr.lua"
copy /Y "%remote_path%\corps\corpSkillBase.lua" "%gameServerPath%\data\corps\corpSkillBase.lua"
copy /Y "%remote_path%\corps\corpSkillLearn.lua" "%gameServerPath%\data\corps\corpSkillLearn.lua"
copy /Y "%remote_path%\corps\corpSkillLevelLearn.lua" "%gameServerPath%\data\corps\corpSkillLevelLearn.lua"
copy /Y "%remote_path%\corps\corpScienceDeviceCost.lua" "%gameServerPath%\data\corps\corpScienceDeviceCost.lua"

copy /Y "%remote_path%\corps\corpActivity.lua" "%gameServerPath%\data\corps\corpActivity.lua"
copy /Y "%remote_path%\corps\corpArchitectureCost.lua" "%gameServerPath%\data\corps\corpArchitectureCost.lua"
copy /Y "%remote_path%\corps\corpArchitectureExchange.lua" "%gameServerPath%\data\corps\corpArchitectureExchange.lua"
copy /Y "%remote_path%\corps\corpDonateCost.lua" "%gameServerPath%\data\corps\corpDonateCost.lua"
copy /Y "%remote_path%\corps\corpDonateLimit.lua" "%gameServerPath%\data\corps\corpDonateLimit.lua"
copy /Y "%remote_path%\corps\corpScienceDeviceCost.lua" "%gameServerPath%\data\corps\corpScienceDeviceCost.lua"
copy /Y "%remote_path%\corps\corpWages.lua" "%gameServerPath%\data\corps\corpWages.lua"
copy /Y "%remote_path%\corps\inheritCommon.lua" "%gameServerPath%\data\corps\inheritCommon.lua"
copy /Y "%remote_path%\corps\inheritExp.lua" "%gameServerPath%\data\corps\inheritExp.lua"
copy /Y "%remote_path%\corps\inheritOfVip.lua" "%gameServerPath%\data\corps\inheritOfVip.lua"
copy /Y "%remote_path%\corps\serverLimitCorpLevel.lua" "%gameServerPath%\data\corps\serverLimitCorpLevel.lua"
copy /Y "%remote_path%\corps\corpsChest.lua" "%gameServerPath%\data\corps\corpsChest.lua"
copy /Y "%remote_path%\corps\corpResourceStore.lua" "%gameServerPath%\data\corps\corpResourceStore.lua"

copy /Y "%remote_path%\corps\corpsWorkPositionShielding.lua" "%gameServerPath%\data\corps\corpsWorkPositionShielding.lua"
copy /Y "%remote_path%\corps\corpsEvent.lua" "%gameServerPath%\data\corps\corpsEvent.lua"

copy /Y "%remote_path%\corps\corpGeneConfig.lua" "%gameServerPath%\data\corps\corpGeneConfig.lua"

copy /Y "%remote_path%\corps\interstellarPirates.lua" "%gameServerPath%\data\raid\interstellarPirates.lua"
copy /Y "%remote_path%\corps\piratesLocation.lua" "%gameServerPath%\data\raid\piratesLocation.lua"
copy /Y "%remote_path%\corps\piratesMonster.lua" "%gameServerPath%\data\raid\piratesMonster.lua"

copy /Y "%remote_path%\raid\corpsBoss\corpsBossDividend.lua" "%gameServerPath%\data\raid\corpsLord\corpsBossDividend.lua"
copy /Y "%remote_path%\raid\corpsBoss\corpsBossRankReward.lua" "%gameServerPath%\data\raid\corpsLord\corpsBossRankReward.lua"
copy /Y "%remote_path%\raid\corpsBoss\corpsBossReward.lua" "%gameServerPath%\data\raid\corpsLord\corpsBossReward.lua"
copy /Y "%remote_path%\raid\corpsBoss\corpsBossConfiguration.lua" "%gameServerPath%\data\raid\corpsLord\corpsBossConfiguration.lua"
copy /Y "%remote_path%\raid\corpsBoss\corpsBossParam.lua" "%gameServerPath%\data\raid\corpsLord\corpsBossParam.lua"

copy /Y "%remote_path%\monster\warriorRoleConfig.lua" "%gameServerPath%\data\monster\warriorRoleConfig.lua"

copy /Y "%remote_path%\raid\legionPrison\legionPrisonDividend.lua" "%gameServerPath%\data\raid\corpsPrison\legionPrisonDividend.lua"
copy /Y "%remote_path%\raid\legionPrison\legionPrisonReward.lua" "%gameServerPath%\data\raid\corpsPrison\legionPrisonReward.lua"
copy /Y "%remote_path%\raid\legionPrison\armyTrialRankReward.lua" "%gameServerPath%\data\raid\corpsPrison\armyTrialRankReward.lua"
copy /Y "%remote_path%\raid\legionPrison\armyTrialConfiguration.lua" "%gameServerPath%\data\raid\corpsPrison\armyTrialConfiguration.lua"
copy /Y "%remote_path%\detector\detectorCommand.lua" "%gameServerPath%\data\config\detector\detectorCommand.lua"
copy /Y "%remote_path%\cutscene\cutsceneConfig.lua" "%gameServerPath%\data\quest\cutsceneConfig.lua"

copy /Y "%remote_path%\raid\kingTrial\kingTrialConfiguration.lua" "%gameServerPath%\data\raid\kingTrial\kingTrialConfiguration.lua"

copy /Y "%remote_path%\redEnvelope\redEnvelope.lua" "%gameServerPath%\data\config\redEnvelope\redEnvelope.lua"
copy /Y "%remote_path%\fragmentCollection\fragmentConfig.lua" "%gameServerPath%\data\fragment\fragmentConfig.lua"
copy /Y "%remote_path%\fragmentCollection\mechaFragmentAwardConfig.lua" "%gameServerPath%\data\fragment\mechaFragmentAwardConfig.lua"
copy /Y "%remote_path%\fragmentCollection\weaponFragmentAwardConfig.lua" "%gameServerPath%\data\fragment\weaponFragmentAwardConfig.lua"
copy /Y "%remote_path%\server\randomRoleNameList.lua" "%gameServerPath%\data\randomName\randomRoleNameList.lua"
copy /Y "%remote_path%\quest\trialQuestAward.lua" "%gameServerPath%\data\quest\trialQuestAward.lua"
copy /Y "%remote_path%\quest\oldTrialQuestAward.lua" "%gameServerPath%\data\quest\oldTrialQuestAward.lua"
copy /Y "%remote_path%\quest\trialQuestData.lua" "%gameServerPath%\data\quest\trialQuestData.lua"
copy /Y "%remote_path%\wardrobe\fashionSetConfig.lua" "%gameServerPath%\data\wardrobe\fashionSetConfig.lua"
copy /Y "%remote_path%\wardrobe\fashionDataConfig.lua" "%gameServerPath%\data\wardrobe\fashionDataConfig.lua"
copy /Y "%remote_path%\wardrobe\MountSetConfig.lua" "%gameServerPath%\data\wardrobe\MountSetConfig.lua"
copy /Y "%remote_path%\wardrobe\MountUnlockCondition.lua" "%gameServerPath%\data\wardrobe\MountUnlockCondition.lua"
copy /Y "%remote_path%\wardrobe\propsOpen.lua" "%gameServerPath%\data\wardrobe\propsOpen.lua"
copy /Y "%remote_path%\airship\airshipConfig.lua" "%gameServerPath%\data\map\mapConfig\airshipConfig.lua"
copy /Y "%remote_path%\quest\chapterData.lua" "%gameServerPath%\data\quest\chapterData.lua"
copy /Y "%remote_path%\newServerActivity\activityCommon.lua" "%gameServerPath%\data\newServerActivity\activityCommon.lua"
copy /Y "%remote_path%\newServerActivity\cropsRaceReward.lua" "%gameServerPath%\data\newServerActivity\cropsRaceReward.lua"
copy /Y "%remote_path%\newServerActivity\lvRaceReward.lua" "%gameServerPath%\data\newServerActivity\lvRaceReward.lua"
copy /Y "%remote_path%\newServerActivity\professionalRaceReward.lua" "%gameServerPath%\data\newServerActivity\professionalRaceReward.lua"
copy /Y "%remote_path%\mirrorRaid\mirrorMapConfig.lua" "%gameServerPath%\data\raid\mirrorMapConfig.lua"
copy /Y "%remote_path%\raid\SamsaraCorridor\ReincarnationBase.lua" "%gameServerPath%\data\raid\SamsaraCorridor\ReincarnationBase.lua"
copy /Y "%remote_path%\raid\SamsaraCorridor\ReincarnationRelation.lua" "%gameServerPath%\data\raid\SamsaraCorridor\ReincarnationRelation.lua"
copy /Y "%remote_path%\raid\SamsaraCorridor\ReincarnationReward.lua" "%gameServerPath%\data\raid\SamsaraCorridor\ReincarnationReward.lua"
copy /Y "%remote_path%\raid\SamsaraCorridor\ReincarnationExp.lua" "%gameServerPath%\data\raid\SamsaraCorridor\ReincarnationExp.lua"
copy /Y "%remote_path%\raid\guideRaid\newPlayerGuideConfig.lua" "%gameServerPath%\data\raid\guideRaid\newPlayerGuideConfig.lua"
copy /Y "%remote_path%\raid\guideRaid\tempSkill.lua" "%gameServerPath%\data\raid\guideRaid\tempSkill.lua"
copy /Y "%remote_path%\raid\imageRaid\robberMonConfig.lua" "%gameServerPath%\data\raid\imageRaid\robberMonConfig.lua"
copy /Y "%remote_path%\server\worldLevel.lua" "%gameServerPath%\data\server\worldLevel.lua"

copy /Y "%remote_path%\life\lifeSkillConst.lua" "%gameServerPath%\data\lifeSkill\lifeSkillConst.lua"
copy /Y "%remote_path%\life\lifeSkillLvInfo.lua" "%gameServerPath%\data\lifeSkill\lifeSkillLvInfo.lua"
copy /Y "%remote_path%\life\lifeSkillType.lua" "%gameServerPath%\data\lifeSkill\lifeSkillType.lua"
copy /Y "%remote_path%\item\randomboxTip.lua" "%gameServerPath%\data\config\item\randomboxTip.lua"
copy /Y "%remote_path%\team\teamGift.lua" "%gameServerPath%\data\team\teamGift.lua"

copy /Y "%remote_path%\expRecovery\expCoefficient.lua" "%gameServerPath%\data\expRetrieve\expCoefficient.lua"
copy /Y "%remote_path%\expRecovery\expRetrieve.lua" "%gameServerPath%\data\expRetrieve\expRetrieve.lua"
copy /Y "%remote_path%\expRecovery\retrieveConfiguration.lua" "%gameServerPath%\data\expRetrieve\retrieveConfiguration.lua"
copy /Y "%remote_path%\activity\AllActivity.lua" "%gameServerPath%\data\activity\allActivity.lua"
copy /Y "%remote_path%\activity\ActiveReward.lua" "%gameServerPath%\data\activity\activeReward.lua"
copy /Y "%remote_path%\activity\newServerAcitvityRule.lua" "%gameServerPath%\data\activity\newServerAcitvityRule.lua"
copy /Y "%remote_path%\activity\registPool.lua" "%gameServerPath%\data\activity\registPool.lua"
copy /Y "%remote_path%\activity\twiceActivity.lua" "%gameServerPath%\data\activity\twiceActivity.lua"
copy /Y "%remote_path%\activity\commonActivityAward.lua" "%gameServerPath%\data\activity\commonActivityAward.lua"
copy /Y "%remote_path%\activity\loginActivity.lua" "%gameServerPath%\data\activity\loginActivity.lua"
copy /Y "%remote_path%\activity\pointAwardActivity.lua" "%gameServerPath%\data\activity\pointAwardActivity.lua"
copy /Y "%remote_path%\activity\composeActivity.lua" "%gameServerPath%\data\activity\composeActivity.lua"
copy /Y "%remote_path%\activity\flowerActivity.lua" "%gameServerPath%\data\activity\flowerActivity.lua"

copy /Y "%remote_path%\gm\realPlayerAttr.lua" "%gameServerPath%\data\starFightingField\realPlayerAttr.lua"
copy /Y "%remote_path%\raid\starFightingField\starFightingFieldCommon.lua" "%gameServerPath%\data\starFightingField\starFightingFieldCommon.lua"
copy /Y "%remote_path%\raid\starFightingField\fightCountPrice.lua" "%gameServerPath%\data\starFightingField\fightCountPrice.lua"
copy /Y "%remote_path%\raid\starFightingField\awardConfig.lua" "%gameServerPath%\data\starFightingField\awardConfig.lua"
copy /Y "%remote_path%\raid\roleEvolution\evolutionRaidOne.lua" "%gameServerPath%\data\roleEvolution\evolutionRaidOne.lua"
copy /Y "%remote_path%\raid\roleEvolution\evolutionRaidTwo.lua" "%gameServerPath%\data\roleEvolution\evolutionRaidTwo.lua"
copy /Y "%remote_path%\raid\roleEvolution\evolutionReward.lua" "%gameServerPath%\data\roleEvolution\evolutionReward.lua"
copy /Y "%remote_path%\raid\roleEvolution\evolutionRewardTwo.lua" "%gameServerPath%\data\roleEvolution\evolutionRewardTwo.lua"
copy /Y "%remote_path%\raid\starFightingField\starFightingFieldRaidConfig.lua" "%gameServerPath%\data\starFightingField\starFightingFieldRaidConfig.lua"
copy /Y "%remote_path%\raid\starFightingField\starFightingFieldReward.lua" "%gameServerPath%\data\starFightingField\starFightingFieldReward.lua"
copy /Y "%remote_path%\raid\starFightingField\mechaHpBuff.lua" "%gameServerPath%\data\starFightingField\mechaHpBuff.lua"

copy /Y "%remote_path%\raid\unionFight\unionFightChapter.lua" "%gameServerPath%\data\raid\unionFight\unionFightChapter.lua"
copy /Y "%remote_path%\raid\unionFight\unionFightRaidConfig.lua" "%gameServerPath%\data\raid\unionFight\unionFightRaidConfig.lua"

copy /Y "%remote_path%\raid\singleCrystalCanyon\robotRelivePos.lua" "%gameServerPath%\data\raid\singleCrystalCanyon\robotRelivePos.lua"

copy /Y "%remote_path%\raid\federalOrder\itemAward.lua" "%gameServerPath%\data\raid\federalOrder\itemAward.lua"
copy /Y "%remote_path%\raid\federalOrder\federalOrderMonConfig.lua" "%gameServerPath%\data\raid\federalOrder\federalOrderMonConfig.lua"
copy /Y "%remote_path%\raid\federalOrder\federalOrderBase.lua" "%gameServerPath%\data\raid\federalOrder\federalOrderBase.lua"
copy /Y "%remote_path%\raid\federalOrder\federalOrderCommon.lua" "%gameServerPath%\data\raid\federalOrder\federalOrderCommon.lua"
copy /Y "%remote_path%\raid\federalOrder\federalOrderRefresh.lua" "%gameServerPath%\data\raid\federalOrder\federalOrderRefresh.lua"
copy /Y "%remote_path%\raid\federalOrder\federalOrderVoiceAnswerQues.lua" "%gameServerPath%\data\raid\federalOrder\federalOrderVoiceAnswerQues.lua"

copy /Y "%remote_path%\operationActivity\specialDrop.lua" "%gameServerPath%\data\operateActivity\specialDrop.lua"
copy /Y "%remote_path%\operationActivity\taskActivity\taskActivityConditions.lua" "%gameServerPath%\data\operateActivity\taskActivityConditions.lua"
copy /Y "%remote_path%\operationActivity\collectionActivity\collectionActivityConditions.lua" "%gameServerPath%\data\operateActivity\collectionActivityConditions.lua"
copy /Y "%remote_path%\operationActivity\popUpActivity\popUpImageDef.lua" "%gameServerPath%\data\operateActivity\popUpImageDef.lua"
copy /Y "%remote_path%\operationActivity\collectionActivity\redeemRewardIndex.lua" "%gameServerPath%\data\operateActivity\redeemRewardIndex.lua"
copy /Y "%remote_path%\operationActivity\giftNum.lua" "%gameServerPath%\data\operateActivity\giftNum.lua"
copy /Y "%remote_path%\tradingRestrictions\restrictedConfiguration.lua" "%gameServerPath%\data\tradingRestrictions\restrictedConfiguration.lua"
copy /Y "%remote_path%\tradingRestrictions\levelGapLimit.lua" "%gameServerPath%\data\tradingRestrictions\levelGapLimit.lua"
copy /Y "%remote_path%\tradingRestrictions\alternateLimitConfig.lua" "%gameServerPath%\data\tradingRestrictions\alternateLimitConfig.lua"

copy /Y "%remote_path%\festivalEvent\newYear\newYearActivityConst.lua" "%gameServerPath%\data\festivalActivity\newYearActivityConst.lua"
copy /Y "%remote_path%\festivalEvent\newYear\newYearCollection.lua" "%gameServerPath%\data\festivalActivity\newYearCollection.lua"
copy /Y "%remote_path%\festivalEvent\newYear\festivalCollectionConfig.lua" "%gameServerPath%\data\festivalActivity\festivalCollectionConfig.lua"
copy /Y "%remote_path%\festivalEvent\newYear\newYearFireworks.lua" "%gameServerPath%\data\festivalActivity\newYearFireworks.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattleBorn.lua" "%gameServerPath%\data\festivalActivity\bombBattleBorn.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattleConst.lua" "%gameServerPath%\data\festivalActivity\bombBattleConst.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattlePos.lua" "%gameServerPath%\data\festivalActivity\bombBattlePos.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattleType.lua" "%gameServerPath%\data\festivalActivity\bombBattleType.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattleAward.lua" "%gameServerPath%\data\festivalActivity\bombBattleAward.lua"
copy /Y "%remote_path%\festivalEvent\newYear\bombBattleAwardFirst.lua" "%gameServerPath%\data\festivalActivity\bombBattleAwardFirst.lua"
copy /Y "%remote_path%\festivalEvent\newYear\newYearExp.lua" "%gameServerPath%\data\festivalActivity\newYearExp.lua"
copy /Y "%remote_path%\festivalEvent\springFestival\crytalTreasureConfig.lua" "%gameServerPath%\data\festivalActivity\crytalTreasureConfig.lua"
copy /Y "%remote_path%\festivalEvent\newYear\mainCityCollectConfig.lua" "%gameServerPath%\data\festivalActivity\mainCityCollectConfig.lua"

copy /Y "%remote_path%\festivalEvent\christmas\snowballCollect.lua" "%gameServerPath%\data\christmas\snowballCollect.lua"
copy /Y "%remote_path%\festivalEvent\christmas\materialLocation.lua" "%gameServerPath%\data\christmas\materialLocation.lua"
copy /Y "%remote_path%\festivalEvent\christmas\snowManConfiguration.lua" "%gameServerPath%\data\christmas\snowManConfiguration.lua"
copy /Y "%remote_path%\festivalEvent\christmas\snowManLocation.lua" "%gameServerPath%\data\christmas\snowManLocation.lua"
copy /Y "%remote_path%\festivalEvent\christmas\snowManMaterial.lua" "%gameServerPath%\data\christmas\snowManMaterial.lua"
copy /Y "%remote_path%\festivalEvent\christmas\snowManGift.lua" "%gameServerPath%\data\christmas\snowManGift.lua"

copy /Y "%remote_path%\newServerActivity\runningGame\runningGameAward.lua" "%gameServerPath%\data\newServerActivity\runningGame\runningGameAward.lua"
copy /Y "%remote_path%\newServerActivity\runningGame\runningGameNpc.lua" "%gameServerPath%\data\newServerActivity\runningGame\runningGameNpc.lua"
copy /Y "%remote_path%\newServerActivity\runningGame\runningGameConfig.lua" "%gameServerPath%\data\newServerActivity\runningGame\runningGameConfig.lua"

copy /Y "%remote_path%\newServerActivity\wishingTree\wishingTreeGift.lua" "%gameServerPath%\data\newServerActivity\wishingTree\wishingTreeGift.lua"

copy /Y "%remote_path%\meridian" "%gameServerPath%\data\config\meridian"
copy /Y "%remote_path%\gene" "%gameServerPath%\data\config\gene"
copy /Y "%remote_path%\energyEquip" "%gameServerPath%\data\config\energyEquip"
copy /Y "%remote_path%\wanderingEarth\escapeSolarSystem" "%gameServerPath%\data\wanderingEarth\escapeSolarSystem"
copy /Y "%remote_path%\wanderingEarth\interstellarExplorSystem" "%gameServerPath%\data\wanderingEarth\interstellarExplor"
copy /Y "%remote_path%\wanderingEarth\rescuePlan" "%gameServerPath%\data\wanderingEarth\rescuePlan"
copy /Y "%remote_path%\wanderingEarth\xearthRedPack" "%gameServerPath%\data\wanderingEarth\springRedPacket"

copy /Y "%remote_path%\server\severHosting.lua" "%gameServerPath%\data\server\serverHosting.lua"
copy /Y "%remote_path%\iOSCelebration\boxPos.lua" "%gameServerPath%\data\iosCelebration\boxPos.lua"
copy /Y "%remote_path%\iOSCelebration\happySevenDayConfig.lua" "%gameServerPath%\data\iosCelebration\happySevenDayConfig.lua"

copy /Y "%remote_path%\store\specialOffersStore\specialStoreTimeLimit.lua" "%gameServerPath%\data\store\specialStoreTimeLimit.lua"
copy /Y "%remote_path%\store\specialOffersStore\limitedTimeGiftBag.lua" "%gameServerPath%\data\store\limitedTimeGiftBag.lua"
copy /Y "%remote_path%\store\specialOffersStore\specialOffersStore.lua" "%gameServerPath%\data\store\specialOffersStore.lua"
copy /Y "%remote_path%\store\rechargeReward.lua" "%gameServerPath%\data\store\rechargeReward.lua"
copy /Y "%remote_path%\crossServer\crossBuffBase.lua" "%gameServerPath%\data\crossServer\crossBuffBase.lua"
copy /Y "%remote_path%\crossServer\crossServerWarPoint.lua" "%gameServerPath%\data\crossServer\crossServerWarPoint.lua"

copy /Y "%remote_path%\transfer" "%gameServerPath%\data\transfer"

copy /Y "%remote_path%\greatGift\greatGiftCondition.lua" "%gameServerPath%\data\greatGift\greatGiftCondition.lua"

copy /Y "%remote_path%\sprint\noahSprintBase.lua" "%gameServerPath%\data\sprint\noahSprintBase.lua"
copy /Y "%remote_path%\sprint\noahSprintMapBlock.lua" "%gameServerPath%\data\sprint\noahSprintMapBlock.lua"
copy /Y "%remote_path%\sprint\sprintRaidReward.lua" "%gameServerPath%\data\sprint\sprintRaidReward.lua"
copy /Y "%remote_path%\sprint\sprintReward.lua" "%gameServerPath%\data\sprint\sprintReward.lua"

copy /Y "%remote_path%\money\exchangeRate.lua" "%gameServerPath%\data\score\exchangeRate.lua"
copy /Y "%remote_path%\mirageBoss" "%gameServerPath%\data\mirageBoss"
copy /Y "%remote_path%\corpsNewServer" "%gameServerPath%\data\corpsNewServer"
copy /Y "%remote_path%\astralBeast\astralBeast.lua" "%gameServerPath%\data\astralBeast\astralBeast.lua"
copy /Y "%remote_path%\astralBeast\astralBeastExp.lua" "%gameServerPath%\data\astralBeast\astralBeastExp.lua"
copy /Y "%remote_path%\astralBeast\astralBeastLv.lua" "%gameServerPath%\data\astralBeast\astralBeastLv.lua"
copy /Y "%remote_path%\astralBeast\astralBeastSkill.lua" "%gameServerPath%\data\astralBeast\astralBeastSkill.lua"
copy /Y "%remote_path%\astralBeast\astralBeastSkillParam.lua" "%gameServerPath%\data\astralBeast\astralBeastSkillParam.lua"
copy /Y "%remote_path%\astralBeast\unlockCondition.lua" "%gameServerPath%\data\astralBeast\unlockCondition.lua"

copy /Y "%remote_path%\mergeServer\collectActivityReward.lua" "%gameServerPath%\data\mergeServer\collectActivityReward.lua"
copy /Y "%remote_path%\mergeServer\crazyGift.lua" "%gameServerPath%\data\mergeServer\crazyGift.lua"
copy /Y "%remote_path%\mergeServer\dropReward.lua" "%gameServerPath%\data\mergeServer\dropReward.lua"
copy /Y "%remote_path%\mergeServer\hotGift.lua" "%gameServerPath%\data\mergeServer\hotGift.lua"
copy /Y "%remote_path%\mergeServer\mergeServerCommon.lua" "%gameServerPath%\data\mergeServer\mergeServerCommon.lua"
copy /Y "%remote_path%\mergeServer\giftGoodsBase.lua" "%gameServerPath%\data\mergeServer\giftGoodsBase.lua"
copy /Y "%remote_path%\mergeServer\mergeServerCollection.lua" "%gameServerPath%\data\mergeServer\mergeServerCollection.lua"
copy /Y "%remote_path%\mergeServer\mergeHistory.lua" "%centerServerPath%\data\mergeServer\mergeHistory.lua"
copy /Y "%remote_path%\mergeServer\mergeHistory.lua" "%gameServerPath%\data\mergeServer\mergeHistory.lua"


copy /Y "%remote_path%\returnPlayer" "%gameServerPath%\data\returnPlayer"
@echo ----------------------------------------------------------------------------------
@echo 拷贝world server配置文件
copy /Y "%remote_path%\activity\activityBase.lua" "%worldServerPath%\data\activity\activityBase.lua"
copy /Y "%remote_path%\team\teamCommonConfig.lua" "%worldServerPath%\data\team\teamCommonConfig.lua"
copy /Y "%remote_path%\team\robotMatchTime.lua" "%worldServerPath%\data\team\robotMatchTime.lua"
copy /Y "%remote_path%\misc\strDef.lua" "%worldServerPath%\data\misc\strDef.lua"
copy /Y "%remote_path%\map\mapConfig.lua" "%worldServerPath%\data\map\mapConfig\mapConfig.lua"
copy /Y "%remote_path%\raid\raidTeamlimit.lua" "%worldServerPath%\data\team\raidTeamlimit.lua"

copy /Y "%remote_path%\raid\raidConfig.lua" "%gameServerPath%\data\team\raidConfig.lua"
copy /Y "%remote_path%\crossServer\crossBuffBase.lua" "%worldServerPath%\data\crossServer\crossBuffBase.lua"
copy /Y "%remote_path%\crossServer\crossServerWarBase.lua" "%worldServerPath%\data\crossServer\crossServerWarBase.lua"
copy /Y "%remote_path%\crossServer\crossServerWarPoint.lua" "%worldServerPath%\data\crossServer\crossServerWarPoint.lua"
copy /Y "%remote_path%\crossServer\crossServerWarTurnDetail.lua" "%worldServerPath%\data\crossServer\crossServerWarTurnDetail.lua"
copy /Y "%remote_path%\crossServer\crossServerRankRate.lua" "%worldServerPath%\data\crossServer\crossServerRankRate.lua"
copy /Y "%remote_path%\crossServer\crossServerWarServerTurn.lua" "%worldServerPath%\data\crossServer\crossServerWarServerTurn.lua"


copy /Y "%remote_path%\raid\raidConfig.lua" "%worldServerPath%\data\team\raidConfig.lua"
copy /Y "%remote_path%\raid\crystalCanyon\battlefieldConfiguration.lua" "%worldServerPath%\data\raid\crystalCanyon\battlefieldConfiguration.lua"
@echo ----------------------------------------------------------------------------------
@echo 拷贝center server配置文件
copy /Y "%remote_path%\mirageBoss" "%centerServerPath%\data\mirageBoss"
copy /Y "%remote_path%\corpsNewServer" "%centerServerPath%\data\corpsNewServer"
copy /Y "%remote_path%\mirageBoss\mirageBossCommon.lua" "%centerServerPath%\data\mirageBoss\mirageBossCommon.lua"
copy /Y "%remote_path%\springActivity\cNYVitalityConfig.lua" "%centerServerPath%\data\springActivity\cNYVitalityConfig.lua"
copy /Y "%remote_path%\springActivity\cNYStoreGoods.lua" "%centerServerPath%\data\springActivity\cNYStoreGoods.lua"
copy /Y "%remote_path%\corps\corpsGrowthQuest.lua" "%centerServerPath%\data\corps\corpsGrowthQuest.lua"
copy /Y "%remote_path%\home\universeEssenceConfig.lua" "%centerServerPath%\data\home\universeEssenceConfig.lua"
copy /Y "%remote_path%\home\universeDistributionConfig.lua" "%centerServerPath%\data\home\universeDistributionConfig.lua"
copy /Y "%remote_path%\home\starResourcePlanetConfig.lua" "%centerServerPath%\data\home\starResourcePlanetConfig.lua"
copy /Y "%remote_path%\home\starDevelopPlanetConfig.lua" "%centerServerPath%\data\home\starDevelopPlanetConfig.lua"
copy /Y "%remote_path%\home\starOccupyingPlanetConfig.lua" "%centerServerPath%\data\home\starOccupyingPlanetConfig.lua"
copy /Y "%remote_path%\home\starOccupyingRankAward.lua" "%centerServerPath%\data\home\starOccupyingRankAward.lua"
copy /Y "%remote_path%\home\homeBuildingConfig.lua" "%centerServerPath%\data\home\homeBuildingConfig.lua"
copy /Y "%remote_path%\home\developmentEvent.lua" "%centerServerPath%\data\home\developmentEvent.lua"
copy /Y "%remote_path%\home\homeConstant.lua" "%centerServerPath%\data\home\homeConstant.lua"
copy /Y "%remote_path%\home\randomEventDataConfig.lua" "%centerServerPath%\data\home\randomEventDataConfig.lua"
copy /Y "%remote_path%\home\randomEventRule.lua" "%centerServerPath%\data\home\randomEventRule.lua"
copy /Y "%remote_path%\home\randomAward.lua" "%centerServerPath%\data\home\randomAward.lua"
copy /Y "%remote_path%\home\searchLogConfig.lua" "%centerServerPath%\data\home\searchLogConfig.lua"
copy /Y "%remote_path%\social\searchLevel.lua" "%centerServerPath%\data\config\search\searchLevel.lua"
copy /Y "%remote_path%\chat\horseLamp.lua" "%centerServerPath%\data\config\horseLamp\horseLampConfig.lua"
copy /Y "%remote_path%\misc\strDef.lua" "%centerServerPath%\data\misc\strDef.lua"

copy /Y "%remote_path%\home\homeWorkshopLimitConfig.lua" "%centerServerPath%\data\home\homeWorkshopLimitConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopMakeConfig.lua" "%centerServerPath%\data\home\homeWorkshopMakeConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopReplaceConfig.lua" "%centerServerPath%\data\home\homeWorkshopReplaceConfig.lua"
copy /Y "%remote_path%\home\homeWorkshopUpConfig.lua" "%centerServerPath%\data\home\homeWorkshopUpConfig.lua"

copy /Y "%remote_path%\mergeServer\collectRankReward.lua" "%centerServerPath%\data\mergeServer\collectRankReward.lua"
copy /Y "%remote_path%\mergeServer\mergeServerActivityDefine.lua" "%centerServerPath%\data\mergeServer\mergeServerActivityDefine.lua"

copy /Y "%remote_path%\raid\SeverLevelRaidCount.lua" "%centerServerPath%\data\config\serverLevel\serverLevelRaidCount.lua"

copy /Y "%remote_path%\common\serverLevelGift.lua" "%centerServerPath%\data\config\serverLevel\serverLevelGift.lua"
copy /Y "%remote_path%\firstWeekRank\firstWeekRankCommonConfig.lua" "%centerServerPath%\data\firstWeekRank\firstWeekRankCommonConfig.lua"
copy /Y "%remote_path%\raid\SeizeTreasureJonsCreateCount.lua" "%centerServerPath%\data\config\seizeTreasureJons\seizeTreasureJonsCreateCount.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\abilityPointAward.lua" "%centerServerPath%\data\config\starArts\abilityPointAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\finalGameGroup.lua" "%centerServerPath%\data\config\starArts\finalGameGroup.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\finalGameRankingAward.lua" "%centerServerPath%\data\config\starArts\finalGameRankingAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\combinePowerRankAward.lua" "%centerServerPath%\data\config\starArts\combinePowerRankAward.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\starBattleConfiguration.lua" "%centerServerPath%\data\config\starArts\starBattleConfiguration.lua"
copy /Y "%remote_path%\raid\starOfMartialArts\quizConfiguration.lua" "%centerServerPath%\data\config\starArts\quizConfiguration.lua"

copy /Y "%remote_path%\raid\worldBoss\worldBossBase.lua" "%centerServerPath%\data\raid\worldBoss\worldBossBase.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCommon.lua" "%centerServerPath%\data\raid\worldBoss\worldBossCommon.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossReward.lua" "%centerServerPath%\data\raid\worldBoss\worldBossReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossParam.lua" "%centerServerPath%\data\raid\worldBoss\worldBossParam.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCoinDrop.lua" "%centerServerPath%\data\raid\worldBoss\worldBossCoinDrop.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPersonGoals.lua" "%centerServerPath%\data\raid\worldBoss\worldBossPersonGoals.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCorpsGoals.lua" "%centerServerPath%\data\raid\worldBoss\worldBossCorpsGoals.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossCommonNew.lua" "%centerServerPath%\data\raid\worldBoss\worldBossCommonNew.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPrepareTimeReward.lua" "%centerServerPath%\data\raid\worldBoss\worldBossPrepareTimeReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossRecommend.lua" "%centerServerPath%\data\raid\worldBoss\worldBossRecommend.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPrepareReward.lua" "%centerServerPath%\data\raid\worldBoss\worldBossPrepareReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossRankReward.lua" "%centerServerPath%\data\raid\worldBoss\worldBossRankReward.lua"
copy /Y "%remote_path%\raid\worldBoss\worldBossPrepareTimeConfig.lua" "%centerServerPath%\data\raid\worldBoss\worldBossPrepareTimeConfig.lua"

copy /Y "%remote_path%\home\villaConfig.lua" "%centerServerPath%\data\home\villaConfig.lua"
copy /Y "%remote_path%\home\roomBuildConfig.lua" "%centerServerPath%\data\home\roomBuildConfig.lua"
copy /Y "%remote_path%\home\furnitureConfig.lua" "%centerServerPath%\data\home\furnitureConfig.lua"
copy /Y "%remote_path%\home\furnitureConstant.lua" "%centerServerPath%\data\home\furnitureConstant.lua"
copy /Y "%remote_path%\home\furnitureResourceAddition.lua" "%centerServerPath%\data\home\furnitureResourceAddition.lua"

copy /Y "%remote_path%\stall\stallPage.lua" "%centerServerPath%\data\config\tradingCenter\stallPage.lua"
copy /Y "%remote_path%\stall\stallEquipLevel.lua" "%centerServerPath%\data\config\tradingCenter\stallEquipLevel.lua"
copy /Y "%remote_path%\stall\aHSysGoods.lua" "%centerServerPath%\data\config\tradingCenter\aHSysGoods.lua"
copy /Y "%remote_path%\item\guidancePrice.lua" "%centerServerPath%\data\config\tradingCenter\guidancePrice.lua"

copy /Y "%remote_path%\raid\kingTrial\corpsIncome.lua" "%centerServerPath%\data\raid\kingTrial\corpsIncome.lua"
copy /Y "%remote_path%\raid\kingTrial\corpsIncomeModulus.lua" "%centerServerPath%\data\raid\kingTrial\corpsIncomeModulus.lua"
copy /Y "%remote_path%\raid\kingTrial\kingTrial.lua" "%centerServerPath%\data\raid\kingTrial\kingTrial.lua"
copy /Y "%remote_path%\raid\kingTrial\kingTrialModulus.lua" "%centerServerPath%\data\raid\kingTrial\kingTrialModulus.lua"
copy /Y "%remote_path%\raid\kingTrial\kingTrialConfiguration.lua" "%centerServerPath%\data\raid\kingTrial\kingTrialConfiguration.lua"
copy /Y "%remote_path%\monster\monsterDrop.lua" "%centerServerPath%\data\monster\monsterDrop.lua"

copy /Y "%remote_path%\activity\AllActivity.lua" "%centerServerPath%\data\activity\allActivity.lua"
copy /Y "%remote_path%\activity\ActiveReward.lua" "%centerServerPath%\data\activity\activeReward.lua"
copy /Y "%remote_path%\activity\newServerAcitvityRule.lua" "%centerServerPath%\data\activity\newServerAcitvityRule.lua"
copy /Y "%remote_path%\activity\unOpenServerActivity.lua" "%centerServerPath%\data\activity\unOpenServerActivity.lua"
copy /Y "%remote_path%\activity\commonActivity.lua" "%centerServerPath%\data\activity\commonActivity.lua"
copy /Y "%remote_path%\activity\subActivity.lua" "%centerServerPath%\data\activity\subActivity.lua"

copy /Y "%remote_path%\home\iExploreConstant.lua" "%centerServerPath%\data\home\iExploreConstant.lua"
copy /Y "%remote_path%\home\homeResLimitConfig.lua" "%centerServerPath%\data\home\homeResLimitConfig.lua"
copy /Y "%remote_path%\home\universeBoxConfig.lua" "%centerServerPath%\data\home\universeBoxConfig.lua"

copy /Y "%remote_path%\msgBox\msgDef.lua" "%centerServerPath%\data\config\msgBox\msgDef.lua"

copy /Y "%remote_path%\raid\peakChallenge\challengeConfiguration.lua" "%centerServerPath%\data\raid\peakChallenge\challengeConfiguration.lua"
copy /Y "%remote_path%\raid\peakChallenge\monsterCoefficient.lua" "%centerServerPath%\data\raid\peakChallenge\monsterCoefficient.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeReward.lua" "%centerServerPath%\data\raid\peakChallenge\challengeReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\playoffsReward.lua" "%centerServerPath%\data\raid\peakChallenge\playoffsReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\peakChallengeConfiguration.lua" "%centerServerPath%\data\raid\peakChallenge\peakChallengeConfiguration.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeReward.lua" "%centerServerPath%\data\raid\peakChallenge\challengeReward.lua"
copy /Y "%remote_path%\raid\peakChallenge\challengeFailReward.lua" "%centerServerPath%\data\raid\peakChallenge\challengeFailReward.lua"
copy /Y "%remote_path%\raid\starbattle" "%centerServerPath%\data\raid\starWar"

copy /Y "%remote_path%\store\goldPurchase.lua" "%centerServerPath%\data\store\goldPurchase.lua"
copy /Y "%remote_path%\store\paymentPoint.lua" "%centerServerPath%\data\store\paymentPoint.lua"
copy /Y "%remote_path%\store\goldStoreForSale.lua" "%centerServerPath%\data\store\goldStoreForSale.lua"
copy /Y "%remote_path%\store\goldStoreRefresh.lua" "%centerServerPath%\data\store\goldStoreRefresh.lua"


copy /Y "%remote_path%\welfare\dailyGiftBag.lua" "%centerServerPath%\data\benefit\dailyGiftBag.lua"
copy /Y "%remote_path%\welfare\dailyGiftDashButtonBag.lua" "%centerServerPath%\data\benefit\dailyGiftDashButtonBag.lua"
copy /Y "%remote_path%\welfare\fund.lua" "%centerServerPath%\data\benefit\fund.lua"
copy /Y "%remote_path%\welfare\ingotGiftBag.lua" "%centerServerPath%\data\benefit\ingotGiftBag.lua"
copy /Y "%remote_path%\welfare\dailySign.lua" "%centerServerPath%\data\benefit\dailySign.lua"
copy /Y "%remote_path%\welfare\accumulativeSign.lua" "%centerServerPath%\data\benefit\accumulativeSign.lua"
copy /Y "%remote_path%\welfare\sevenDayPackage.lua" "%centerServerPath%\data\benefit\sevenDayPackage.lua"

copy /Y "%remote_path%\stall\boothConfiguration.lua" "%centerServerPath%\data\config\tradingCenter\boothConfiguration.lua"
copy /Y "%remote_path%\stall\boothCoordinates.lua" "%centerServerPath%\data\config\tradingCenter\boothCoordinates.lua"

copy /Y "%remote_path%\corps\corpsCommon.lua" "%centerServerPath%\data\corps\corpsCommon.lua"
copy /Y "%remote_path%\corps\coprsGetByCorpsBoss.lua" "%centerServerPath%\data\corps\coprsGetByCorpsBoss.lua"
copy /Y "%remote_path%\corps\coprsGetByKingTrial.lua" "%centerServerPath%\data\corps\coprsGetByKingTrial.lua"
copy /Y "%remote_path%\corps\coprsGetByPeople.lua" "%centerServerPath%\data\corps\coprsGetByPeople.lua"
copy /Y "%remote_path%\corps\coprsGetByStarWar.lua" "%centerServerPath%\data\corps\coprsGetByStarWar.lua"
copy /Y "%remote_path%\corps\coprsGetByWorldBoss.lua" "%centerServerPath%\data\corps\coprsGetByWorldBoss.lua"
copy /Y "%remote_path%\corps\coprsGetByWorldBossType.lua" "%centerServerPath%\data\corps\coprsGetByWorldBossType.lua"
copy /Y "%remote_path%\corps\corpActivity.lua" "%centerServerPath%\data\corps\corpActivity.lua"
copy /Y "%remote_path%\corps\corpArchitectureCost.lua" "%centerServerPath%\data\corps\corpArchitectureCost.lua"
copy /Y "%remote_path%\corps\corpArchitectureExchange.lua" "%centerServerPath%\data\corps\corpArchitectureExchange.lua"
copy /Y "%remote_path%\corps\corpDonateCost.lua" "%centerServerPath%\data\corps\corpDonateCost.lua"
copy /Y "%remote_path%\corps\corpDonateLimit.lua" "%centerServerPath%\data\corps\corpDonateLimit.lua"
copy /Y "%remote_path%\corps\corpScienceDeviceCost.lua" "%centerServerPath%\data\corps\corpScienceDeviceCost.lua"
copy /Y "%remote_path%\corps\corpWages.lua" "%centerServerPath%\data\corps\corpWages.lua"
copy /Y "%remote_path%\corps\inheritCommon.lua" "%centerServerPath%\data\corps\inheritCommon.lua"
copy /Y "%remote_path%\corps\inheritExp.lua" "%centerServerPath%\data\corps\inheritExp.lua"
copy /Y "%remote_path%\corps\serverLimitCorpLevel.lua" "%centerServerPath%\data\corps\serverLimitCorpLevel.lua"

copy /Y "%remote_path%\corps\inheritCommon.lua" "%centerServerPath%\data\corps\inheritCommon.lua"
copy /Y "%remote_path%\corps\inheritExp.lua" "%centerServerPath%\data\corps\inheritExp.lua"
copy /Y "%remote_path%\corps\corpsEvent.lua" "%centerServerPath%\data\corps\corpsEvent.lua"
copy /Y "%remote_path%\corps\corpsManagerGift.lua" "%centerServerPath%\data\corps\corpsManagerGift.lua"
copy /Y "%remote_path%\corps\personRedpackMap.lua" "%centerServerPath%\data\corps\personRedpackMap.lua"

copy /Y "%remote_path%\newRecruitsCorps\newRecruitsCorpsCommon.lua" "%centerServerPath%\data\corps\newRecruitsCorpsCommon.lua"
copy /Y "%remote_path%\newRecruitsCorps\newRecruitsCorpsSystemMember.lua" "%centerServerPath%\data\corps\newRecruitsCorpsSystemMember.lua"

copy /Y "%remote_path%\corpsParty\corpPartyBase.lua" "%centerServerPath%\data\raid\corpsParty\corpPartyBase.lua"
copy /Y "%remote_path%\corpsParty\corpPartyExp.lua" "%centerServerPath%\data\raid\corpsParty\corpPartyExp.lua"
copy /Y "%remote_path%\corpsParty\corpPartyIndex.lua" "%centerServerPath%\data\raid\corpsParty\corpPartyIndex.lua"
copy /Y "%remote_path%\corpsParty\corpQuestion.lua" "%centerServerPath%\data\raid\corpsParty\corpQuestion.lua"
copy /Y "%remote_path%\corpsParty\corpQuestionReward.lua" "%centerServerPath%\data\raid\corpsParty\corpQuestionReward.lua"
copy /Y "%remote_path%\corpsParty\partyBoxLocation.lua" "%centerServerPath%\data\raid\corpsParty\partyBoxLocation.lua"
copy /Y "%remote_path%\corpsParty\partyChangeModel.lua" "%centerServerPath%\data\raid\corpsParty\partyChangeModel.lua"
copy /Y "%remote_path%\corpsParty\partyCollection.lua" "%centerServerPath%\data\raid\corpsParty\partyCollection.lua"

copy /Y "%remote_path%\raid\serverbattle\serverBattleSeasonAward.lua" "%centerServerPath%\data\raid\serverBattle\serverBattleSeasonAward.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceAward.lua" "%centerServerPath%\data\raid\serverBattle\serverBattlePerRaceAward.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceWinTimeRate.lua" "%centerServerPath%\data\raid\serverBattle\serverBattlePerRaceWinTimeRate.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattleSpecialAward.lua" "%centerServerPath%\data\raid\serverBattle\serverBattleSpecialAward.lua"
copy /Y "%remote_path%\raid\serverbattle\serverBattlePerRaceTreasureBox.lua" "%centerServerPath%\data\raid\serverBattle\serverBattlePerRaceTreasureBox.lua"

copy /Y "%remote_path%\vIP\vipBase.lua" "%centerServerPath%\data\vip\vipBase.lua"
copy /Y "%remote_path%\vIP\vipPower.lua" "%centerServerPath%\data\vip\vipPower.lua"

copy /Y "%remote_path%\pveTower\rankingsAward.lua" "%centerServerPath%\data\raid\pveTower\rankingsAward.lua"
copy /Y "%remote_path%\pveTower\pveTowerBase.lua" "%centerServerPath%\data\raid\pveTower\pveTowerBase.lua"
copy /Y "%remote_path%\pveTower\oldLevelConfig.lua" "%centerServerPath%\data\raid\pveTower\oldLevelConfig.lua"
copy /Y "%remote_path%\common\serverLevel.lua" "%centerServerPath%\data\config\serverLevel\serverLevel.lua"
copy /Y "%remote_path%\raid\crystalCanyon\battlefieldConfiguration.lua" "%centerServerPath%\data\raid\crystalCanyon\battlefieldConfiguration.lua"
copy /Y "%remote_path%\raid\crystalCanyon\battlefieldSetting.lua" "%centerServerPath%\data\raid\crystalCanyon\battlefieldSetting.lua"

copy /Y "%remote_path%\redEnvelope\redEnvelopeConfiguration.lua" "%centerServerPath%\data\config\redEnvelope\redEnvelopeConfiguration.lua"
copy /Y "%remote_path%\redEnvelope\redEnvelope.lua" "%centerServerPath%\data\config\redEnvelope\redEnvelope.lua"
copy /Y "%remote_path%\equip\EquipLevel.lua" "%centerServerPath%\data\config\item\EquipLevel.lua"

copy /Y "%remote_path%\raid\legionPrison\legionPrisonDividend.lua" "%centerServerPath%\data\raid\corpsPrison\legionPrisonDividend.lua"
copy /Y "%remote_path%\raid\legionPrison\legionPrisonReward.lua" "%centerServerPath%\data\raid\corpsPrison\legionPrisonReward.lua"
copy /Y "%remote_path%\raid\legionPrison\armyTrialRankReward.lua" "%centerServerPath%\data\raid\corpsPrison\armyTrialRankReward.lua"
copy /Y "%remote_path%\raid\legionPrison\armyTrialConfiguration.lua" "%centerServerPath%\data\raid\corpsPrison\armyTrialConfiguration.lua"
copy /Y "%remote_path%\newServerActivity\activityCommon.lua" "%centerServerPath%\data\newServerActivity\activityCommon.lua"
copy /Y "%remote_path%\newServerActivity\cropsRaceReward.lua" "%centerServerPath%\data\newServerActivity\cropsRaceReward.lua"
copy /Y "%remote_path%\newServerActivity\lvRaceReward.lua" "%centerServerPath%\data\newServerActivity\lvRaceReward.lua"
copy /Y "%remote_path%\newServerActivity\professionalRaceReward.lua" "%centerServerPath%\data\newServerActivity\professionalRaceReward.lua"
copy /Y "%remote_path%\newServerActivity\runningGame\runningGameConfig.lua" "%centerServerPath%\data\newServerActivity\runningGame\runningGameConfig.lua"
copy /Y "%remote_path%\newServerActivity\runningGame\runningGameRankAward.lua" "%centerServerPath%\data\newServerActivity\runningGame\runningGameRankAward.lua"
copy /Y "%remote_path%\newServerActivity\runningGame\runningGameNpc.lua" "%centerServerPath%\data\newServerActivity\runningGame\runningGameNpc.lua"
copy /Y "%remote_path%\newServerActivity\wishingTree\wishingTreeDayAward.lua" "%centerServerPath%\data\newServerActivity\wishingTree\wishingTreeDayAward.lua"
copy /Y "%remote_path%\newServerActivity\wishingTree\wishingTreeAward.lua" "%centerServerPath%\data\newServerActivity\wishingTree\wishingTreeAward.lua"
copy /Y "%remote_path%\newServerActivity\wishingTree\wishingTreeConfig.lua" "%centerServerPath%\data\newServerActivity\wishingTree\wishingTreeConfig.lua"

copy /Y "%remote_path%\rank\rankAward.lua" "%centerServerPath%\data\rank\rankAward.lua"
copy /Y "%remote_path%\friend\recommandConfig.lua" "%centerServerPath%\data\friend\recommandConfig.lua"

copy /Y "%remote_path%\wardrobe\fashionSetConfig.lua" "%centerServerPath%\data\wardrobe\fashionSetConfig.lua"
copy /Y "%remote_path%\wardrobe\fashionDataConfig.lua" "%centerServerPath%\data\wardrobe\fashionDataConfig.lua"


copy /Y "%remote_path%\militaryRank\militaryRankChildType.lua" "%centerServerPath%\data\starFightingField\militaryRankChildType.lua"
copy /Y "%remote_path%\raid\starFightingField\dropRank.lua" "%centerServerPath%\data\starFightingField\dropRank.nk.lua"
copy /Y "%remote_path%\raid\starFightingField\robotBase.lua" "%centerServerPath%\data\starFightingField\robotBase.lua"
copy /Y "%remote_path%\raid\starFightingField\robotMechaBase.lua" "%centerServerPath%\data\starFightingField\robotMechaBase.lua"
copy /Y "%remote_path%\raid\starFightingField\starFightingFieldCommon.lua" "%centerServerPath%\data\starFightingField\starFightingFieldCommon.lua"
copy /Y "%remote_path%\raid\starFightingField\targetSelectRule.lua" "%centerServerPath%\data\starFightingField\targetSelectRule.lua"
copy /Y "%remote_path%\raid\starFightingField\awardConfig.lua" "%centerServerPath%\data\starFightingField\awardConfig.lua"
copy /Y "%remote_path%\raid\starFightingField\robotName.lua" "%centerServerPath%\data\starFightingField\robotName.lua"
copy /Y "%remote_path%\raid\starFightingField\divisionConfig.lua" "%centerServerPath%\data\starFightingField\divisionConfig.lua"


copy /Y "%remote_path%\operationActivity\operateActivityBase.lua" "%centerServerPath%\data\operateActivity\operateActivityBase.lua"
copy /Y "%remote_path%\operationActivity\operateActivityTime.lua" "%centerServerPath%\data\operateActivity\operateActivityTime.lua"
copy /Y "%remote_path%\operationActivity\treasureSeek\treasureSeekAward.lua" "%centerServerPath%\data\operateActivity\treasureSeekAward.lua"
copy /Y "%remote_path%\operationActivity\treasureSeek\treasureSeekAwardType.lua" "%centerServerPath%\data\operateActivity\treasureSeekAwardType.lua"
copy /Y "%remote_path%\operationActivity\treasureSeek\treasureSeekBase.lua" "%centerServerPath%\data\operateActivity\treasureSeekBase.lua"


copy /Y "%remote_path%\festivalEvent\newYear\festivalActivity.lua" "%centerServerPath%\data\festivalActivity\festivalActivity.lua"
copy /Y "%remote_path%\festivalEvent\springFestival\springFestivalTime.lua" "%centerServerPath%\data\festivalActivity\springFestivalTime.lua"

copy /Y "%remote_path%\tradingRestrictions\auctionLimit.lua" "%centerServerPath%\data\tradingRestrictions\auctionLimit.lua"
copy /Y "%remote_path%\tradingRestrictions\dailyRecharge.lua" "%centerServerPath%\data\tradingRestrictions\dailyRecharge.lua"
copy /Y "%remote_path%\tradingRestrictions\historicalRecharge.lua" "%centerServerPath%\data\tradingRestrictions\historicalRecharge.lua"
copy /Y "%remote_path%\tradingRestrictions\legionDonation.lua" "%centerServerPath%\data\tradingRestrictions\legionDonation.lua"
copy /Y "%remote_path%\tradingRestrictions\restrictedConfiguration.lua" "%centerServerPath%\data\tradingRestrictions\restrictedConfiguration.lua"

copy /Y "%remote_path%\redEnvelope\newYearRedType.lua" "%centerServerPath%\data\config\redEnvelope\newYearRedType.lua"
copy /Y "%remote_path%\redEnvelope\newYearSpecialRedType.lua" "%centerServerPath%\data\config\redEnvelope\newYearSpecialRedType.lua"
copy /Y "%remote_path%\redEnvelope\newYearSpecialRedTypeMoney.lua" "%centerServerPath%\data\config\redEnvelope\newYearSpecialRedTypeMoney.lua"
copy /Y "%remote_path%\redEnvelope\serverBattleRedEnvelope.lua" "%centerServerPath%\data\config\redEnvelope\serverBattleRedEnvelope.lua"

copy /Y "%remote_path%\festivalEvent\christmas\snowballCollect.lua" "%centerServerPath%\data\christmas\snowballCollect.lua"
copy /Y "%remote_path%\festivalEvent\christmas\snowManConfiguration.lua" "%centerServerPath%\data\christmas\snowManConfiguration.lua"
copy /Y "%remote_path%\misc\sysMail.lua" "%centerServerPath%\data\misc\sysMail.lua"

copy /Y "%remote_path%\activity\activityTimeConfig.lua" "%centerServerPath%\data\activity\activityTimeConfig.lua"
copy /Y "%remote_path%\wanderingEarth\escapeSolarSystem" "%centerServerPath%\data\wanderingEarth\escapeSolarSystem"
copy /Y "%remote_path%\wanderingEarth\interstellarExplorSystem" "%centerServerPath%\data\wanderingEarth\interstellarExplor"
copy /Y "%remote_path%\wanderingEarth\rescuePlan" "%centerServerPath%\data\wanderingEarth\rescuePlan"
copy /Y "%remote_path%\wanderingEarth\xearthRedPack" "%centerServerPath%\data\wanderingEarth\springRedPacket"

copy /Y "%remote_path%\stall\stallPotionLevel.lua" "%centerServerPath%\data\config\tradingCenter\stallPotionLevel.lua"
copy /Y "%remote_path%\iOSCelebration\boxPos.lua" "%centerServerPath%\data\iosCelebration\boxPos.lua"
copy /Y "%remote_path%\iOSCelebration\happySevenDayConfig.lua" "%centerServerPath%\data\iosCelebration\happySevenDayConfig.lua"
copy /Y "%remote_path%\store\limitedTimeStore.lua" "%centerServerPath%\data\store\limitedTimeStore.lua"
copy /Y "%remote_path%\store\specialOffersStore\specialOffersStore.lua" "%centerServerPath%\data\store\specialOffersStore.lua"
copy /Y "%remote_path%\store\storeItemSet.lua" "%centerServerPath%\data\store\storeItemSet.lua"

copy /Y "%remote_path%\stall\corpAHTipsConfiguration.lua" "%centerServerPath%\data\corpAH\corpAHTipsConfiguration.lua"

copy /Y "%remote_path%\greatGift\greatGiftCondition.lua" "%centerServerPath%\data\greatGift\greatGiftCondition.lua"
copy /Y "%remote_path%\greatGift\greatGiftBase.lua" "%centerServerPath%\data\greatGift\greatGiftBase.lua"
copy /Y "%remote_path%\greatGift\greatGiftAwardConfig.lua" "%centerServerPath%\data\greatGift\greatGiftAwardConfig.lua"

copy /Y "%remote_path%\festivalStore\festivalStoreGoods.lua" "%centerServerPath%\data\festivalStore\festivalStoreGoods.lua"
copy /Y "%remote_path%\festivalStore\festivalStorePage.lua" "%centerServerPath%\data\festivalStore\festivalStorePage.lua"

copy /Y "%remote_path%\battle\passiveSkillStatusLevelUpCost.lua" "%centerServerPath%\data\battle\passiveSkillStatusLevelUpCost.lua"
copy /Y "%remote_path%\crossServer\crossBuffBase.lua" "%centerServerPath%\data\crossServer\crossBuffBase.lua"

copy /Y "%remote_path%\flowerRank\flowerSpecialRankConfig.lua" "%centerServerPath%\data\flowerRank\flowerSpecialRankConfig.lua"
copy /Y "%remote_path%\flowerRank\flowerSpecialTips.lua" "%centerServerPath%\data\flowerRank\flowerSpecialTips.lua"

@echo ----------------------------------------------------------------------------------
@echo 拷贝Login Server配置文件
copy /Y "%remote_path%\map\mapConfig.lua" "%loginServerPath%\data\map\mapConfig\mapConfig.lua"
copy /Y "%remote_path%\server\randomRoleNameList.lua" "%loginServerPath%\data\randomName\randomRoleNameList.lua"
copy /Y "%remote_path%\tradingRestrictions\restrictedConfiguration.lua" "%loginServerPath%\data\tradingRestrictions\restrictedConfiguration.lua"
copy /Y "%remote_path%\server\severHosting.lua" "%loginServerPath%\data\serverHosting\serverHosting.lua"
copy /Y "%remote_path%\misc\strDef.lua" "%loginServerPath%\data\misc\strDef.lua"
copy /Y "%remote_path%\activity\registPool.lua" "%loginServerPath%\data\activity\registPool.lua"

@echo ----------------------------------------------------------------------------------
@echo 拷贝Active Server配置文件
copy /Y "%remote_path%\activity\AllActivity.lua" "%activeServerPath%\data\activity\allActivity.lua"

@echo ----------------------------------------------------------------------------------
@echo 拷贝公用文件
copy /Y "%remote_path%\common\openLv.lua" "%commonPath%\common\openLv.lua"
copy /Y "%remote_path%\common\clientVersion.lua" "%commonPath%\common\clientVersion.lua"
copy /Y "%remote_path%\common\ChannelToServerList.lua" "%commonPath%\common\ChannelToServerList.lua"
copy /Y "%remote_path%\common\ChannelToVersion.lua" "%commonPath%\common\ChannelToVersion.lua"

@echo ----------------------------------------------------------------------------------
@echo 拷贝Public Server配置文件

@echo ----------------------------------------------------------------------------------
@echo 拷贝Merge Server配置文件
copy /Y "%remote_path%\mergeServer\mergeCompensate.lua" "%mergeServerPath%\data\config\mergeCompensate.lua"

@echo ----------------------------------------------------------------------------------
@echo 拷贝offlineAI文件
copy /Y "%remote_path%\battle" "%offlineAiPath%\data\config\battle"
copy /Y "%remote_path%\map\mapConfig.lua" "%offlineAiPath%\data\map\mapConfig\mapConfig.lua"
copy /Y "%remote_path%\map\gameServerInitMapConfig.lua" "%offlineAiPath%\data\map\mapConfig\gameServerInitMapConfig.lua"
copy /Y "%remote_path%\map\mapPkType.lua" "%offlineAiPath%\data\map\mapConfig\mapPkType.lua"
copy /Y "%remote_path%\map\transportData.lua" "%offlineAiPath%\data\map\mapConfig\mapTransportConfig.lua"
copy /Y "%remote_map%\mapEditData" "%offlineAiPath%\data\map\mapEditData"
copy /Y "%remote_map%\navmeshFile" "%offlineAiPath%\data\map\navmeshFile"
copy /Y "%remote_path%\airship\airshipConfig.lua" "%offlineAiPath%\data\map\mapConfig\airshipConfig.lua"
copy /Y "%remote_path%\mecha\mechaAbilityGroup.lua" "%offlineAiPath%\data\mecha\mechaAbilityGroup.lua"
copy /Y "%remote_path%\mecha\mechaAbilityGroupRollValue.lua" "%offlineAiPath%\data\mecha\mechaAbilityGroupRollValue.lua"
::copy /Y "%remote_path%\mecha\mechaArmsGroup.lua" "%offlineAiPath%\data\mecha\mechaArmsGroup.lua"
copy /Y "%remote_path%\mecha\mechaAdvance.lua" "%offlineAiPath%\data\mecha\mechaAdvance.lua"
copy /Y "%remote_path%\mecha\mechaBase.lua" "%offlineAiPath%\data\mecha\mechaBase.lua"
copy /Y "%remote_path%\mecha\mechaBattleAttr.lua" "%offlineAiPath%\data\mecha\mechaBattleAttr.lua"
copy /Y "%remote_path%\mecha\mechaBattleCount.lua" "%offlineAiPath%\data\mecha\mechaBattleCount.lua"
copy /Y "%remote_path%\mecha\mechaBorn.lua" "%offlineAiPath%\data\mecha\mechaBorn.lua"
copy /Y "%remote_path%\mecha\mechaCommon.lua" "%offlineAiPath%\data\mecha\mechaCommon.lua"
copy /Y "%remote_path%\mecha\mechaDevice.lua" "%offlineAiPath%\data\mecha\mechaDevice.lua"
copy /Y "%remote_path%\mecha\mechaDeviceGroup.lua" "%offlineAiPath%\data\mecha\mechaDeviceGroup.lua"
copy /Y "%remote_path%\mecha\mechaDeviceLv.lua" "%offlineAiPath%\data\mecha\mechaDeviceLv.lua"
copy /Y "%remote_path%\mecha\mechaExp.lua" "%offlineAiPath%\data\mecha\mechaExp.lua"
copy /Y "%remote_path%\mecha\mechaGuard.lua" "%offlineAiPath%\data\mecha\mechaGuard.lua"
copy /Y "%remote_path%\mecha\mechaGuardRandom.lua" "%offlineAiPath%\data\mecha\mechaGuardRandom.lua"
copy /Y "%remote_path%\mecha\mechaInitAttr.lua" "%offlineAiPath%\data\mecha\mechaInitAttr.lua"
copy /Y "%remote_path%\mecha\mechaSkillDesc.lua" "%offlineAiPath%\data\mecha\mechaSkillDesc.lua"
::copy /Y "%remote_path%\mecha\mechaStunt.lua" "%offlineAiPath%\data\mecha\mechaStunt.lua"
::copy /Y "%remote_path%\mecha\mechaTalent.lua" "%offlineAiPath%\data\mecha\mechaTalent.lua"
copy /Y "%remote_path%\mecha\mechaZizhidan.lua" "%offlineAiPath%\data\mecha\mechaZizhidan.lua"
copy /Y "%remote_path%\mecha\mechaBattleAttr.lua" "%offlineAiPath%\data\mecha\mechaBattleAttr.lua"
copy /Y "%remote_path%\mecha\mechaFourAttr.lua" "%offlineAiPath%\data\mecha\mechaFourAttr.lua"
copy /Y "%remote_path%\mecha\mechaCorpSkill.lua" "%offlineAiPath%\data\mecha\mechaCorpSkill.lua"
copy /Y "%remote_path%\monster\monsterBase.lua" "%offlineAiPath%\data\monster\monsterBase.lua"
copy /Y "%remote_path%\quest\questData.lua" "%offlineAiPath%\data\quest\questData.lua"
copy /Y "%remote_path%\quest\questBuffAction.lua" "%offlineAiPath%\data\quest\questBuffAction.lua"
copy /Y "%remote_path%\quest\questTransmit.lua" "%offlineAiPath%\data\quest\questTransmit.lua"
copy /Y "%remote_path%\quest\questServerLimit.lua" "%offlineAiPath%\data\quest\questServerLimit.lua"
copy /Y "%remote_path%\quest\questSpecialPush.lua" "%offlineAiPath%\data\quest\questSpecialPush.lua"
copy /Y "%remote_path%\quest\questStepData.lua" "%offlineAiPath%\data\quest\questStepData.lua"
copy /Y "%remote_path%\quest\questRewardData.lua" "%offlineAiPath%\data\quest\questRewardData.lua"
copy /Y "%remote_path%\quest\subStepData.lua" "%offlineAiPath%\data\quest\subStepData.lua"
copy /Y "%remote_path%\quest\federalQuestAward.lua" "%offlineAiPath%\data\quest\federalQuestAward.lua"
copy /Y "%remote_path%\quest\questEquipAttr.lua" "%offlineAiPath%\data\quest\questEquipAttr.lua"

copy /Y "%remote_path%\server\voting.lua" "%gameServerPath%\data\server\voting.lua"
@echo ----------------------------------------------------------------------------------
@echo 配置文件拷贝结束
if '%1' equ '' (@pause)
